package cloud.omas.sdk.generator.go;

import io.swagger.v3.oas.models.media.ObjectSchema;
import io.swagger.v3.oas.models.media.Schema;
import org.openapitools.codegen.ClientOptInput;
import org.openapitools.codegen.DefaultGenerator;
import org.openapitools.codegen.config.CodegenConfigurator;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.concurrent.Callable;
import java.util.stream.Stream;

@Command(
        name = "go",
        description = "Generate the Go SDK.",
        mixinStandardHelpOptions = true)
public final class OmasGoGeneratorApplication implements Callable<Integer> {

    @Option(
            names = {"-s", "--service"},
            defaultValue = "metrics",
            split = ",",
            paramLabel = "<name>",
            description = "Service to generate; may be repeated or comma-separated.")
    private List<String> services;

    @Override
    public Integer call() {
        generateServices(services);
        return 0;
    }

    public static void generateServices(List<String> serviceNames) {
        serviceNames.forEach(OmasGoGeneratorApplication::generate);
    }

    private static void generate(String serviceName) {
        Path output = Path.of("go", serviceName);
        try {
            removeGeneratedFiles(output);
        } catch (IOException exception) {
            throw new IllegalStateException("Cannot clean generated Go sources for " + serviceName, exception);
        }
        CodegenConfigurator configurator = new CodegenConfigurator()
                .setGeneratorName("omas-go")
                .setInputSpec(Path.of("schema", serviceName + ".yaml").toString())
                .setOutputDir(output.toString())
                .setApiPackage(serviceName)
                .setModelPackage(serviceName)
                .addGlobalProperty("apis", "")
                .addGlobalProperty("models", "")
                .addGlobalProperty("apiTests", "false")
                .addGlobalProperty("apiDocs", "false")
                .addGlobalProperty("modelTests", "false")
                .addGlobalProperty("modelDocs", "false")
                .addGlobalProperty("supportingFiles", "")
                .addAdditionalProperty("disallowAdditionalPropertiesIfNotPresent", "false")
                .addAdditionalProperty("enumClassPrefix", "true")
                .addAdditionalProperty("hideGenerationTimestamp", "true")
                .addAdditionalProperty("isGoSubmodule", "true")
                .addAdditionalProperty("packageName", serviceName)
                .addAdditionalProperty("serviceName", serviceName)
                .addAdditionalProperty("sourceFolder", "generated");
        ClientOptInput input = configurator.toClientOptInput();
        flattenConditionalSchemas(input);
        DefaultGenerator generator = new DefaultGenerator();
        generator.setGenerateMetadata(false);
        generator.opts(input).generate();
        try {
            formatGeneratedFiles(output);
        } catch (IOException exception) {
            throw new IllegalStateException("Cannot format generated Go sources for " + serviceName, exception);
        }
    }

    static void removeGeneratedFiles(Path output) throws IOException {
        if (!Files.isDirectory(output)) {
            return;
        }
        try (Stream<Path> paths = Files.walk(output)) {
            for (Path path : paths.filter(Files::isRegularFile).toList()) {
                String source = Files.readString(path);
                if (source.contains("Code generated by the Omas Go SDK generator. DO NOT EDIT.")) {
                    Files.delete(path);
                }
            }
        }
    }

    static void formatGeneratedFiles(Path output) throws IOException {
        if (!Files.isDirectory(output)) {
            return;
        }
        try (Stream<Path> paths = Files.walk(output)) {
            List<Path> goFiles = paths
                    .filter(Files::isRegularFile)
                    .filter(path -> path.getFileName().toString().endsWith(".go"))
                    .sorted()
                    .toList();
            for (Path goFile : goFiles) {
                Process process = new ProcessBuilder("gofmt", "-w", goFile.toString())
                        .inheritIO()
                        .start();
                int exitCode;
                try {
                    exitCode = process.waitFor();
                } catch (InterruptedException exception) {
                    Thread.currentThread().interrupt();
                    throw new IOException("Interrupted while formatting " + goFile, exception);
                }
                if (exitCode != 0) {
                    throw new IOException("gofmt failed for " + goFile + " with exit code " + exitCode);
                }
            }
        }
    }

    private static void flattenConditionalSchemas(ClientOptInput input) {
        if (input.getOpenAPI().getComponents() == null || input.getOpenAPI().getComponents().getSchemas() == null) {
            return;
        }
        input.getOpenAPI().getComponents().getSchemas().replaceAll((name, schema) -> {
            if (schema.getProperties() != null && !schema.getProperties().isEmpty()
                    && schema.getOneOf() != null && !schema.getOneOf().isEmpty()) {
                ObjectSchema flattened = new ObjectSchema();
                flattened.setTitle(schema.getTitle());
                flattened.setDescription(schema.getDescription());
                flattened.setProperties(schema.getProperties());
                flattened.setRequired(schema.getRequired());
                flattened.setAdditionalProperties(schema.getAdditionalProperties());
                flattened.setNullable(schema.getNullable());
                flattened.setReadOnly(schema.getReadOnly());
                flattened.setWriteOnly(schema.getWriteOnly());
                flattened.setDeprecated(schema.getDeprecated());
                flattened.setExample(schema.getExample());
                flattened.setExtensions(schema.getExtensions());
                return flattened;
            }
            return schema;
        });
    }
}
