package cloud.omas.sdk.generator.python;

import cloud.omas.sdk.generator.common.ApiErrorCatalog;
import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.Operation;
import io.swagger.v3.oas.models.PathItem;
import io.swagger.v3.oas.models.Paths;
import io.swagger.v3.oas.models.media.Content;
import io.swagger.v3.oas.models.media.ArraySchema;
import io.swagger.v3.oas.models.media.IntegerSchema;
import io.swagger.v3.oas.models.media.MediaType;
import io.swagger.v3.oas.models.media.ObjectSchema;
import io.swagger.v3.oas.models.media.StringSchema;
import io.swagger.v3.oas.models.parameters.PathParameter;
import io.swagger.v3.oas.models.parameters.QueryParameter;
import io.swagger.v3.oas.models.parameters.RequestBody;
import io.swagger.v3.oas.models.responses.ApiResponse;
import io.swagger.v3.oas.models.responses.ApiResponses;
import io.swagger.v3.oas.models.servers.Server;
import org.openapitools.codegen.ClientOptInput;
import org.openapitools.codegen.DefaultGenerator;
import org.openapitools.codegen.config.GlobalSettings;
import io.swagger.v3.parser.OpenAPIV3Parser;
import org.testng.annotations.Test;

import java.io.IOException;
import java.math.BigDecimal;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.stream.Stream;

import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertFalse;
import static org.testng.Assert.assertNotNull;
import static org.testng.Assert.assertTrue;

@SuppressWarnings({"rawtypes", "unchecked"})
public class OmasPythonClientCodegenTest {

    @Test
    public void testCoversEveryMetricsOperationAndKnownError() {
        Path contract = Path.of("..", "schema", "metrics.yaml").toAbsolutePath().normalize();
        OpenAPI openAPI = new OpenAPIV3Parser().read(contract.toString());
        assertNotNull(openAPI);
        Set<String> operationIds = new TreeSet<>();
        openAPI.getPaths().values().forEach(path -> path.readOperations().forEach(
                operation -> operationIds.add(operation.getOperationId())));
        Set<String> errorCodes = new TreeSet<>();
        ApiErrorCatalog.discover(openAPI).forEach(error -> errorCodes.add(error.errorCode()));

        OmasPythonClientCodegen codegen = new OmasPythonClientCodegen();
        codegen.additionalProperties().put("serviceName", "metrics");
        codegen.processOpts();
        codegen.preprocessOpenAPI(openAPI);

        List<Map<String, Object>> operations = (List<Map<String, Object>>)
                codegen.additionalProperties().get("clientOperations");
        List<Map<String, Object>> errors = (List<Map<String, Object>>)
                codegen.additionalProperties().get("serviceErrors");
        Set<String> generatedOperations = new TreeSet<>();
        operations.forEach(operation -> generatedOperations.add(operation.get("operationId").toString()));
        Set<String> generatedErrors = new TreeSet<>();
        errors.forEach(error -> generatedErrors.add(error.get("errorCode").toString()));

        assertEquals(generatedOperations, operationIds);
        assertEquals(generatedOperations.size(), 24);
        assertEquals(generatedErrors, errorCodes);
    }

    @Test
    public void testCleanupIgnoresBinaryCachesAndHandwrittenSources() throws IOException {
        Path output = Files.createTempDirectory("omas-python-cleanup-");
        try {
            Path generated = output.resolve("generated.py");
            Path handwritten = output.resolve("facade.py");
            Path cache = output.resolve("models.pyc");
            Files.writeString(generated, "# Code generated by the Omas Python SDK generator. DO NOT EDIT.\n");
            Files.writeString(handwritten, "value = 1\n");
            Files.write(cache, new byte[]{(byte) 0xff, 0x00});

            OmasPythonGeneratorApplication.removeGeneratedFiles(output);

            assertFalse(Files.exists(generated));
            assertTrue(Files.exists(handwritten));
            assertTrue(Files.exists(cache));
        } finally {
            deleteTree(output);
        }
    }

    @Test
    public void testGeneratesFlatModelsSyncAsyncClientsAndTypedErrors() throws IOException {
        ObjectSchema payload = new ObjectSchema();
        payload.addProperty("message", new StringSchema().minLength(2).maxLength(20));
        payload.addProperty("alias", new StringSchema());
        payload.setRequired(List.of("message"));
        Operation operation = new Operation()
                .operationId("send")
                .addParametersItem(new PathParameter()
                        .name("id")
                        .required(true)
                        .schema(new StringSchema()))
                .addParametersItem(new QueryParameter()
                        .name("limit")
                        .schema(new IntegerSchema()
                                .format("int32")
                                .minimum(BigDecimal.ONE)
                                .maximum(BigDecimal.TEN)))
                .addParametersItem(new QueryParameter()
                        .name("statuses")
                        .schema(new ArraySchema()
                                .items(new StringSchema())
                                .uniqueItems(true)))
                .requestBody(new RequestBody().required(true).content(
                        new Content().addMediaType("application/json", new MediaType().schema(payload))))
                .responses(new ApiResponses().addApiResponse("200", new ApiResponse()
                        .description("sent")
                        .content(new Content().addMediaType(
                                "application/json",
                                new MediaType().schema(new ObjectSchema()
                                        .$ref("#/components/schemas/SendResponse"))))));
        ObjectSchema notFound = new ObjectSchema();
        notFound.addProperty("errorCode", new StringSchema()._enum(List.of("RESOURCE_NOT_FOUND")));
        notFound.addProperty("error", new StringSchema());
        notFound.setRequired(List.of("errorCode", "error"));
        OpenAPI openAPI = new OpenAPI()
                .servers(List.of(new Server().url("https://api.example.test/")))
                .components(new Components()
                        .addSchemas("SendResponse", new ObjectSchema()
                                .addProperty("accepted", new StringSchema()))
                        .addSchemas("SendStatus", new StringSchema()
                                ._enum(List.of("READY", "NOT_READY")))
                        .addSchemas("ResourceNotFoundException", notFound))
                .paths(new Paths().addPathItem("/items/{id}", new PathItem().post(operation)));
        Path output = Files.createTempDirectory("omas-python-model-");
        try {
            generate(openAPI, output);
            String models = Files.readString(findFile(output, "models.py"));
            String client = Files.readString(findFile(output, "client.py"));
            String errors = Files.readString(findFile(output, "errors.py"));
            String metadata = Files.readString(findFile(output, "metadata.py"));

            assertTrue(models.contains("class SendOperationRequest(_SdkModel):"), models);
            assertTrue(models.contains("id: str"), models);
            assertTrue(models.contains("limit: int | None"), models);
            assertTrue(models.contains("message: str"), models);
            assertTrue(models.contains("alias: str | None"), models);
            assertTrue(models.contains("class SendStatus(StrEnum):"), models);
            assertTrue(models.contains("READY = \"READY\""), models);
            assertTrue(models.contains("NOT_READY = \"NOT_READY\""), models);
            assertTrue(models.contains("AfterValidator(_unique_items)"), models);
            assertTrue(client.contains("class MetricsClient:"), client);
            assertTrue(client.contains("class AsyncMetricsClient:"), client);
            assertTrue(client.contains("def send("), client);
            assertTrue(client.contains("async def send("), client);
            assertTrue(client.contains("request.id"), client);
            assertTrue(client.contains("query[\"limit\"] = wire[\"limit\"]"), client);
            assertTrue(client.contains("body[\"message\"] = wire[\"message\"]"), client);
            assertFalse(client.contains("body[\"id\"]"), client);
            assertTrue(errors.contains("class ResourceNotFoundError(ApiError[Any]):"), errors);
            assertTrue(errors.contains("\"RESOURCE_NOT_FOUND\": ResourceNotFoundError"), errors);
            assertTrue(metadata.contains("CONTRACT_DIGEST"), metadata);
        } finally {
            deleteTree(output);
        }
    }

    private static void generate(OpenAPI openAPI, Path output) {
        GlobalSettings.setProperty("apiTests", "false");
        GlobalSettings.setProperty("apiDocs", "false");
        GlobalSettings.setProperty("modelTests", "false");
        GlobalSettings.setProperty("modelDocs", "false");
        GlobalSettings.setProperty("supportingFiles", "");
        GlobalSettings.setProperty("models", "");
        GlobalSettings.setProperty("apis", "false");
        OmasPythonClientCodegen codegen = new OmasPythonClientCodegen();
        codegen.setOutputDir(output.toString());
        codegen.setApiPackage("");
        codegen.setModelPackage("");
        codegen.additionalProperties().put("serviceName", "metrics");
        codegen.additionalProperties().put("sourceFolder", "");
        codegen.additionalProperties().put("contractDigest", "abc123");
        try {
            new DefaultGenerator(false)
                    .opts(new ClientOptInput().config(codegen).openAPI(openAPI))
                    .generate();
        } finally {
            GlobalSettings.reset();
        }
    }

    private static Path findFile(Path root, String filename) throws IOException {
        try (Stream<Path> paths = Files.walk(root)) {
            return paths.filter(path -> path.getFileName().toString().equals(filename))
                    .findFirst()
                    .orElseThrow(() -> new AssertionError("Generated file not found: " + filename));
        }
    }

    private static void deleteTree(Path root) throws IOException {
        try (Stream<Path> paths = Files.walk(root)) {
            for (Path path : paths.sorted(Comparator.reverseOrder()).toList()) {
                Files.deleteIfExists(path);
            }
        }
    }
}
