package cloud.omas.sdk.generator.typescript;

import org.openapitools.codegen.ClientOptInput;
import org.openapitools.codegen.DefaultGenerator;
import org.openapitools.codegen.config.CodegenConfigurator;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.HexFormat;
import java.util.List;
import java.util.concurrent.Callable;
import java.util.stream.Stream;

@Command(
        name = "typescript",
        description = "Generate the TypeScript SDK.",
        mixinStandardHelpOptions = true)
public final class OmasTypeScriptGeneratorApplication implements Callable<Integer> {

    @Option(
            names = {"-s", "--service"},
            defaultValue = "metrics",
            split = ",",
            paramLabel = "<name>",
            description = "Service to generate; may be repeated or comma-separated.")
    private List<String> services;

    @Override
    public Integer call() {
        generateServices(services);
        return 0;
    }

    public static void generateServices(List<String> serviceNames) {
        serviceNames.forEach(OmasTypeScriptGeneratorApplication::generate);
    }

    private static void generate(String serviceName) {
        Path schema = Path.of("schema", serviceName + ".yaml");
        Path output = Path.of("typescript", serviceName, "src", "generated");
        try {
            removeGeneratedFiles(output);
        } catch (IOException exception) {
            throw new IllegalStateException(
                    "Cannot clean generated TypeScript sources for " + serviceName,
                    exception);
        }
        CodegenConfigurator configurator = new CodegenConfigurator()
                .setGeneratorName("omas-typescript")
                .setInputSpec(schema.toString())
                .setOutputDir(output.toString())
                .setApiPackage("")
                .setModelPackage("models")
                .addGlobalProperty("apiTests", "false")
                .addGlobalProperty("apiDocs", "false")
                .addGlobalProperty("modelTests", "false")
                .addGlobalProperty("modelDocs", "false")
                .addAdditionalProperty("hideGenerationTimestamp", "true")
                .addAdditionalProperty("contractDigest", digestUnchecked(schema))
                .addAdditionalProperty("generatorVersion", "1.0.0")
                .addAdditionalProperty("serviceName", serviceName);
        ClientOptInput input = configurator.toClientOptInput();
        DefaultGenerator generator = new DefaultGenerator();
        generator.setGenerateMetadata(false);
        generator.opts(input).generate();
        try {
            formatGeneratedFiles(output);
        } catch (IOException exception) {
            throw new IllegalStateException(
                    "Cannot format generated TypeScript sources for " + serviceName,
                    exception);
        }
    }

    static void removeGeneratedFiles(Path output) throws IOException {
        if (!Files.isDirectory(output)) {
            return;
        }
        try (Stream<Path> paths = Files.walk(output)) {
            for (Path path : paths.filter(Files::isRegularFile).toList()) {
                String source = Files.readString(path);
                if (source.contains(
                        "Code generated by the Omas TypeScript SDK generator. DO NOT EDIT.")) {
                    Files.delete(path);
                }
            }
        }
    }

    static String contractDigest(Path schema) throws IOException {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            return HexFormat.of().formatHex(digest.digest(Files.readAllBytes(schema)));
        } catch (NoSuchAlgorithmException exception) {
            throw new IllegalStateException("SHA-256 is not available", exception);
        }
    }

    static void formatGeneratedFiles(Path output) throws IOException {
        if (!Files.isDirectory(output)) {
            return;
        }
        try (Stream<Path> paths = Files.walk(output)) {
            List<Path> typeScriptFiles = paths
                    .filter(Files::isRegularFile)
                    .filter(path -> path.getFileName().toString().endsWith(".ts"))
                    .sorted()
                    .toList();
            if (typeScriptFiles.isEmpty()) {
                return;
            }
            List<String> command = new ArrayList<>(List.of(
                    "pnpm",
                    "--dir",
                    typeScriptWorkspace().toString(),
                    "exec",
                    "biome",
                    "format",
                    "--write"));
            typeScriptFiles.stream()
                    .map(Path::toAbsolutePath)
                    .map(Path::normalize)
                    .map(Path::toString)
                    .forEach(command::add);
            Process process = new ProcessBuilder(command).inheritIO().start();
            int exitCode;
            try {
                exitCode = process.waitFor();
            } catch (InterruptedException exception) {
                Thread.currentThread().interrupt();
                throw new IOException("Interrupted while formatting generated TypeScript", exception);
            }
            if (exitCode != 0) {
                throw new IOException("Biome failed with exit code " + exitCode);
            }
        }
    }

    private static Path typeScriptWorkspace() throws IOException {
        for (Path candidate : List.of(Path.of("typescript"), Path.of("..", "typescript"))) {
            Path workspace = candidate.toAbsolutePath().normalize();
            if (Files.isRegularFile(workspace.resolve("package.json"))) {
                return workspace;
            }
        }
        throw new IOException("Cannot locate the TypeScript workspace");
    }

    private static String digestUnchecked(Path schema) {
        try {
            return contractDigest(schema);
        } catch (IOException exception) {
            throw new IllegalStateException("Cannot read public contract " + schema, exception);
        }
    }
}
