package cloud.omas.sdk.generator.python;

import org.openapitools.codegen.ClientOptInput;
import org.openapitools.codegen.DefaultGenerator;
import org.openapitools.codegen.config.CodegenConfigurator;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;
import java.util.List;
import java.util.concurrent.Callable;
import java.util.stream.Stream;

@Command(
        name = "python",
        description = "Generate the Python SDK.",
        mixinStandardHelpOptions = true)
public final class OmasPythonGeneratorApplication implements Callable<Integer> {

    @Option(
            names = {"-s", "--service"},
            defaultValue = "metrics",
            split = ",",
            paramLabel = "<name>",
            description = "Service to generate; may be repeated or comma-separated.")
    private List<String> services;

    @Override
    public Integer call() {
        generateServices(services);
        return 0;
    }

    public static void generateServices(List<String> serviceNames) {
        serviceNames.forEach(OmasPythonGeneratorApplication::generate);
    }

    private static void generate(String serviceName) {
        Path schema = Path.of("schema", serviceName + ".yaml");
        Path output = Path.of(
                "python", serviceName, "src", "omascloud", "sdk", serviceName, "generated");
        try {
            removeGeneratedFiles(output);
        } catch (IOException exception) {
            throw new IllegalStateException("Cannot clean generated Python sources for " + serviceName, exception);
        }
        CodegenConfigurator configurator = new CodegenConfigurator()
                .setGeneratorName("omas-python")
                .setInputSpec(schema.toString())
                .setOutputDir(output.toString())
                .setApiPackage("")
                .setModelPackage("")
                .addGlobalProperty("apiTests", "false")
                .addGlobalProperty("apiDocs", "false")
                .addGlobalProperty("modelTests", "false")
                .addGlobalProperty("modelDocs", "false")
                .addAdditionalProperty("hideGenerationTimestamp", "true")
                .addAdditionalProperty("contractDigest", digestUnchecked(schema))
                .addAdditionalProperty("generatorVersion", "1.0.0")
                .addAdditionalProperty("serviceName", serviceName)
                .addAdditionalProperty("sourceFolder", "");
        ClientOptInput input = configurator.toClientOptInput();
        DefaultGenerator generator = new DefaultGenerator();
        generator.setGenerateMetadata(false);
        generator.opts(input).generate();
        try {
            formatGeneratedFiles(output);
        } catch (IOException exception) {
            throw new IllegalStateException("Cannot format generated Python sources for " + serviceName, exception);
        }
    }

    static void removeGeneratedFiles(Path output) throws IOException {
        if (!Files.isDirectory(output)) {
            return;
        }
        try (Stream<Path> paths = Files.walk(output)) {
            for (Path path : paths
                    .filter(Files::isRegularFile)
                    .filter(candidate -> candidate.getFileName().toString().endsWith(".py"))
                    .toList()) {
                if (Files.readString(path).contains(
                        "Code generated by the Omas Python SDK generator. DO NOT EDIT.")) {
                    Files.delete(path);
                }
            }
        }
    }

    static String contractDigest(Path schema) throws IOException {
        try {
            return HexFormat.of().formatHex(
                    MessageDigest.getInstance("SHA-256").digest(Files.readAllBytes(schema)));
        } catch (NoSuchAlgorithmException exception) {
            throw new IllegalStateException("SHA-256 is not available", exception);
        }
    }

    static void formatGeneratedFiles(Path output) throws IOException {
        if (!Files.isDirectory(output)) {
            return;
        }
        runFormatter(List.of("ruff", "format", output.toString()));
        runFormatter(List.of("ruff", "check", "--fix", output.toString()));
        runFormatter(List.of("ruff", "format", output.toString()));
        runFormatter(List.of("ruff", "check", output.toString()));
    }

    private static void runFormatter(List<String> command) throws IOException {
        Process process = new ProcessBuilder(command).inheritIO().start();
        int exitCode;
        try {
            exitCode = process.waitFor();
        } catch (InterruptedException exception) {
            Thread.currentThread().interrupt();
            throw new IOException("Interrupted while formatting generated Python", exception);
        }
        if (exitCode != 0) {
            throw new IOException("Ruff failed with exit code " + exitCode);
        }
    }

    private static String digestUnchecked(Path schema) {
        try {
            return contractDigest(schema);
        } catch (IOException exception) {
            throw new IllegalStateException("Cannot read public contract " + schema, exception);
        }
    }
}
