// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

import (
	"encoding/json"

	"github.com/omascloud/sdks/go/core"
)

// AccessDeniedError represents the ACCESS_DENIED API error.
type AccessDeniedError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *AccessDeniedError) Unwrap() error {
	return e.APIError
}

// AccountNotActiveError represents the ACCOUNT_NOT_ACTIVE API error.
type AccountNotActiveError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *AccountNotActiveError) Unwrap() error {
	return e.APIError
}

// AlarmDatapointsExceedEvaluationBucketsError represents the ALARM_DATAPOINTS_EXCEED_EVALUATION_BUCKETS API error.
type AlarmDatapointsExceedEvaluationBucketsError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *AlarmDatapointsExceedEvaluationBucketsError) Unwrap() error {
	return e.APIError
}

// AlarmEvaluationPeriodNotMultipleOfResolutionError represents the ALARM_EVALUATION_PERIOD_NOT_MULTIPLE_OF_RESOLUTION API error.
type AlarmEvaluationPeriodNotMultipleOfResolutionError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *AlarmEvaluationPeriodNotMultipleOfResolutionError) Unwrap() error {
	return e.APIError
}

// AlarmEvaluationWindowTooLargeError represents the ALARM_EVALUATION_WINDOW_TOO_LARGE API error.
type AlarmEvaluationWindowTooLargeError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *AlarmEvaluationWindowTooLargeError) Unwrap() error {
	return e.APIError
}

// ChartsOverlapError represents the CHARTS_OVERLAP API error.
type ChartsOverlapError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *ChartsOverlapError) Unwrap() error {
	return e.APIError
}

// ChartColumnInvalidError represents the CHART_COLUMN_INVALID API error.
type ChartColumnInvalidError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *ChartColumnInvalidError) Unwrap() error {
	return e.APIError
}

// ChartColSpanInvalidError represents the CHART_COL_SPAN_INVALID API error.
type ChartColSpanInvalidError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *ChartColSpanInvalidError) Unwrap() error {
	return e.APIError
}

// ChartExceedsDashboardWidthError represents the CHART_EXCEEDS_DASHBOARD_WIDTH API error.
type ChartExceedsDashboardWidthError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *ChartExceedsDashboardWidthError) Unwrap() error {
	return e.APIError
}

// ChartRowInvalidError represents the CHART_ROW_INVALID API error.
type ChartRowInvalidError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *ChartRowInvalidError) Unwrap() error {
	return e.APIError
}

// ChartRowSpanInvalidError represents the CHART_ROW_SPAN_INVALID API error.
type ChartRowSpanInvalidError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *ChartRowSpanInvalidError) Unwrap() error {
	return e.APIError
}

// ChartVariableTypeRequiredError represents the CHART_VARIABLE_TYPE_REQUIRED API error.
type ChartVariableTypeRequiredError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *ChartVariableTypeRequiredError) Unwrap() error {
	return e.APIError
}

// ChartVariableVisibleRequiredError represents the CHART_VARIABLE_VISIBLE_REQUIRED API error.
type ChartVariableVisibleRequiredError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *ChartVariableVisibleRequiredError) Unwrap() error {
	return e.APIError
}

// ContradictoryDashboardFilterError represents the CONTRADICTORY_DASHBOARD_FILTER API error.
type ContradictoryDashboardFilterError struct {
	*core.APIError
	Details *ContradictoryDashboardFilterExceptionDetails
}

// Unwrap exposes the shared API error fields.
func (e *ContradictoryDashboardFilterError) Unwrap() error {
	return e.APIError
}

// CyclicDashboardVariableDependencyError represents the CYCLIC_DASHBOARD_VARIABLE_DEPENDENCY API error.
type CyclicDashboardVariableDependencyError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *CyclicDashboardVariableDependencyError) Unwrap() error {
	return e.APIError
}

// DashboardRefreshIntervalRequiredError represents the DASHBOARD_REFRESH_INTERVAL_REQUIRED API error.
type DashboardRefreshIntervalRequiredError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *DashboardRefreshIntervalRequiredError) Unwrap() error {
	return e.APIError
}

// DashboardRefreshIntervalTooFastError represents the DASHBOARD_REFRESH_INTERVAL_TOO_FAST API error.
type DashboardRefreshIntervalTooFastError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *DashboardRefreshIntervalTooFastError) Unwrap() error {
	return e.APIError
}

// DuplicateAlarmVariableNameError represents the DUPLICATE_ALARM_VARIABLE_NAME API error.
type DuplicateAlarmVariableNameError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *DuplicateAlarmVariableNameError) Unwrap() error {
	return e.APIError
}

// DuplicateChartIdError represents the DUPLICATE_CHART_ID API error.
type DuplicateChartIdError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *DuplicateChartIdError) Unwrap() error {
	return e.APIError
}

// DuplicateChartVariableNameError represents the DUPLICATE_CHART_VARIABLE_NAME API error.
type DuplicateChartVariableNameError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *DuplicateChartVariableNameError) Unwrap() error {
	return e.APIError
}

// DuplicateDashboardFilterError represents the DUPLICATE_DASHBOARD_FILTER API error.
type DuplicateDashboardFilterError struct {
	*core.APIError
	Details *DuplicateDashboardFilterExceptionDetails
}

// Unwrap exposes the shared API error fields.
func (e *DuplicateDashboardFilterError) Unwrap() error {
	return e.APIError
}

// DuplicateDimensionNameError represents the DUPLICATE_DIMENSION_NAME API error.
type DuplicateDimensionNameError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *DuplicateDimensionNameError) Unwrap() error {
	return e.APIError
}

// EmailNotificationChannelCannotIncludeWebhookConfigError represents the EMAIL_NOTIFICATION_CHANNEL_CANNOT_INCLUDE_WEBHOOK_CONFIG API error.
type EmailNotificationChannelCannotIncludeWebhookConfigError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *EmailNotificationChannelCannotIncludeWebhookConfigError) Unwrap() error {
	return e.APIError
}

// EmailNotificationChannelConfigRequiredError represents the EMAIL_NOTIFICATION_CHANNEL_CONFIG_REQUIRED API error.
type EmailNotificationChannelConfigRequiredError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *EmailNotificationChannelConfigRequiredError) Unwrap() error {
	return e.APIError
}

// EntryRequiresValueOrStatisticSetError represents the ENTRY_REQUIRES_VALUE_OR_STATISTIC_SET API error.
type EntryRequiresValueOrStatisticSetError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *EntryRequiresValueOrStatisticSetError) Unwrap() error {
	return e.APIError
}

// EntryTimestampInFutureError represents the ENTRY_TIMESTAMP_IN_FUTURE API error.
type EntryTimestampInFutureError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *EntryTimestampInFutureError) Unwrap() error {
	return e.APIError
}

// EntryTimestampTooOldError represents the ENTRY_TIMESTAMP_TOO_OLD API error.
type EntryTimestampTooOldError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *EntryTimestampTooOldError) Unwrap() error {
	return e.APIError
}

// ExpressionTooComplexError represents the EXPRESSION_TOO_COMPLEX API error.
type ExpressionTooComplexError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *ExpressionTooComplexError) Unwrap() error {
	return e.APIError
}

// ExpressionVariableExpressionRequiredError represents the EXPRESSION_VARIABLE_EXPRESSION_REQUIRED API error.
type ExpressionVariableExpressionRequiredError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *ExpressionVariableExpressionRequiredError) Unwrap() error {
	return e.APIError
}

// InvalidAggregationError represents the INVALID_AGGREGATION API error.
type InvalidAggregationError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *InvalidAggregationError) Unwrap() error {
	return e.APIError
}

// InvalidAlarmRequestError represents the INVALID_ALARM_REQUEST API error.
type InvalidAlarmRequestError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *InvalidAlarmRequestError) Unwrap() error {
	return e.APIError
}

// InvalidDashboardFilterError represents the INVALID_DASHBOARD_FILTER API error.
type InvalidDashboardFilterError struct {
	*core.APIError
	Details *InvalidDashboardFilterExceptionDetails
}

// Unwrap exposes the shared API error fields.
func (e *InvalidDashboardFilterError) Unwrap() error {
	return e.APIError
}

// InvalidDashboardTimeRangeError represents the INVALID_DASHBOARD_TIME_RANGE API error.
type InvalidDashboardTimeRangeError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *InvalidDashboardTimeRangeError) Unwrap() error {
	return e.APIError
}

// InvalidExpressionError represents the INVALID_EXPRESSION API error.
type InvalidExpressionError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *InvalidExpressionError) Unwrap() error {
	return e.APIError
}

// InvalidExpressionTokenError represents the INVALID_EXPRESSION_TOKEN API error.
type InvalidExpressionTokenError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *InvalidExpressionTokenError) Unwrap() error {
	return e.APIError
}

// InvalidMetricDataError represents the INVALID_METRIC_DATA API error.
type InvalidMetricDataError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *InvalidMetricDataError) Unwrap() error {
	return e.APIError
}

// InvalidMetricQueryError represents the INVALID_METRIC_QUERY API error.
type InvalidMetricQueryError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *InvalidMetricQueryError) Unwrap() error {
	return e.APIError
}

// InvalidNumericExpressionError represents the INVALID_NUMERIC_EXPRESSION API error.
type InvalidNumericExpressionError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *InvalidNumericExpressionError) Unwrap() error {
	return e.APIError
}

// InvalidOrExpiredVerificationCodeError represents the INVALID_OR_EXPIRED_VERIFICATION_CODE API error.
type InvalidOrExpiredVerificationCodeError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *InvalidOrExpiredVerificationCodeError) Unwrap() error {
	return e.APIError
}

// InvalidPaginationTokenError represents the INVALID_PAGINATION_TOKEN API error.
type InvalidPaginationTokenError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *InvalidPaginationTokenError) Unwrap() error {
	return e.APIError
}

// MetricQueryTimestampInFutureError represents the METRIC_QUERY_TIMESTAMP_IN_FUTURE API error.
type MetricQueryTimestampInFutureError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *MetricQueryTimestampInFutureError) Unwrap() error {
	return e.APIError
}

// MetricQueryTimestampTooOldError represents the METRIC_QUERY_TIMESTAMP_TOO_OLD API error.
type MetricQueryTimestampTooOldError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *MetricQueryTimestampTooOldError) Unwrap() error {
	return e.APIError
}

// MetricVariableMetricNameRequiredError represents the METRIC_VARIABLE_METRIC_NAME_REQUIRED API error.
type MetricVariableMetricNameRequiredError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *MetricVariableMetricNameRequiredError) Unwrap() error {
	return e.APIError
}

// MismatchedExpressionParenthesesError represents the MISMATCHED_EXPRESSION_PARENTHESES API error.
type MismatchedExpressionParenthesesError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *MismatchedExpressionParenthesesError) Unwrap() error {
	return e.APIError
}

// MissingExpressionOperandError represents the MISSING_EXPRESSION_OPERAND API error.
type MissingExpressionOperandError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *MissingExpressionOperandError) Unwrap() error {
	return e.APIError
}

// MissingExpressionOperandsError represents the MISSING_EXPRESSION_OPERANDS API error.
type MissingExpressionOperandsError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *MissingExpressionOperandsError) Unwrap() error {
	return e.APIError
}

// NotificationChannelConfigRequiredError represents the NOTIFICATION_CHANNEL_CONFIG_REQUIRED API error.
type NotificationChannelConfigRequiredError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *NotificationChannelConfigRequiredError) Unwrap() error {
	return e.APIError
}

// NotificationChannelInUseError represents the NOTIFICATION_CHANNEL_IN_USE API error.
type NotificationChannelInUseError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *NotificationChannelInUseError) Unwrap() error {
	return e.APIError
}

// OnlyEmailNotificationChannelsCanBeVerifiedError represents the ONLY_EMAIL_NOTIFICATION_CHANNELS_CAN_BE_VERIFIED API error.
type OnlyEmailNotificationChannelsCanBeVerifiedError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *OnlyEmailNotificationChannelsCanBeVerifiedError) Unwrap() error {
	return e.APIError
}

// ResourceDeletionInProgressError represents the RESOURCE_DELETION_IN_PROGRESS API error.
type ResourceDeletionInProgressError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *ResourceDeletionInProgressError) Unwrap() error {
	return e.APIError
}

// ResourceLimitExceededError represents the RESOURCE_LIMIT_EXCEEDED API error.
type ResourceLimitExceededError struct {
	*core.APIError
	Details *ResourceLimitExceededExceptionDetails
}

// Unwrap exposes the shared API error fields.
func (e *ResourceLimitExceededError) Unwrap() error {
	return e.APIError
}

// ResourceNotFoundError represents the RESOURCE_NOT_FOUND API error.
type ResourceNotFoundError struct {
	*core.APIError
	Details *ResourceNotFoundExceptionDetails
}

// Unwrap exposes the shared API error fields.
func (e *ResourceNotFoundError) Unwrap() error {
	return e.APIError
}

// ResourceUpdatedConcurrentlyError represents the RESOURCE_UPDATED_CONCURRENTLY API error.
type ResourceUpdatedConcurrentlyError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *ResourceUpdatedConcurrentlyError) Unwrap() error {
	return e.APIError
}

// StartTimeAfterEndTimeError represents the START_TIME_AFTER_END_TIME API error.
type StartTimeAfterEndTimeError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *StartTimeAfterEndTimeError) Unwrap() error {
	return e.APIError
}

// StatisticSetIncompleteError represents the STATISTIC_SET_INCOMPLETE API error.
type StatisticSetIncompleteError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *StatisticSetIncompleteError) Unwrap() error {
	return e.APIError
}

// StatisticSetInvalidRangeError represents the STATISTIC_SET_INVALID_RANGE API error.
type StatisticSetInvalidRangeError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *StatisticSetInvalidRangeError) Unwrap() error {
	return e.APIError
}

// TokenExpiredError represents the TOKEN_EXPIRED API error.
type TokenExpiredError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *TokenExpiredError) Unwrap() error {
	return e.APIError
}

// TooManyDimensionsError represents the TOO_MANY_DIMENSIONS API error.
type TooManyDimensionsError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *TooManyDimensionsError) Unwrap() error {
	return e.APIError
}

// TooManyDimensionCombinationsError represents the TOO_MANY_DIMENSION_COMBINATIONS API error.
type TooManyDimensionCombinationsError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *TooManyDimensionCombinationsError) Unwrap() error {
	return e.APIError
}

// UnauthorizedError represents the UNAUTHORIZED API error.
type UnauthorizedError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *UnauthorizedError) Unwrap() error {
	return e.APIError
}

// UnsupportedChartVariableTypeError represents the UNSUPPORTED_CHART_VARIABLE_TYPE API error.
type UnsupportedChartVariableTypeError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *UnsupportedChartVariableTypeError) Unwrap() error {
	return e.APIError
}

// UnverifiedNotificationChannelError represents the UNVERIFIED_NOTIFICATION_CHANNEL API error.
type UnverifiedNotificationChannelError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *UnverifiedNotificationChannelError) Unwrap() error {
	return e.APIError
}

// WebhookNotificationChannelCannotIncludeEmailConfigError represents the WEBHOOK_NOTIFICATION_CHANNEL_CANNOT_INCLUDE_EMAIL_CONFIG API error.
type WebhookNotificationChannelCannotIncludeEmailConfigError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *WebhookNotificationChannelCannotIncludeEmailConfigError) Unwrap() error {
	return e.APIError
}

// WebhookNotificationChannelConfigRequiredError represents the WEBHOOK_NOTIFICATION_CHANNEL_CONFIG_REQUIRED API error.
type WebhookNotificationChannelConfigRequiredError struct {
	*core.APIError
}

// Unwrap exposes the shared API error fields.
func (e *WebhookNotificationChannelConfigRequiredError) Unwrap() error {
	return e.APIError
}

func decodeAPIError(apiError *core.APIError) error {
	switch apiError.ErrorCode {
	case "ACCESS_DENIED":
		return &AccessDeniedError{APIError: apiError}
	case "ACCOUNT_NOT_ACTIVE":
		return &AccountNotActiveError{APIError: apiError}
	case "ALARM_DATAPOINTS_EXCEED_EVALUATION_BUCKETS":
		return &AlarmDatapointsExceedEvaluationBucketsError{APIError: apiError}
	case "ALARM_EVALUATION_PERIOD_NOT_MULTIPLE_OF_RESOLUTION":
		return &AlarmEvaluationPeriodNotMultipleOfResolutionError{APIError: apiError}
	case "ALARM_EVALUATION_WINDOW_TOO_LARGE":
		return &AlarmEvaluationWindowTooLargeError{APIError: apiError}
	case "CHARTS_OVERLAP":
		return &ChartsOverlapError{APIError: apiError}
	case "CHART_COLUMN_INVALID":
		return &ChartColumnInvalidError{APIError: apiError}
	case "CHART_COL_SPAN_INVALID":
		return &ChartColSpanInvalidError{APIError: apiError}
	case "CHART_EXCEEDS_DASHBOARD_WIDTH":
		return &ChartExceedsDashboardWidthError{APIError: apiError}
	case "CHART_ROW_INVALID":
		return &ChartRowInvalidError{APIError: apiError}
	case "CHART_ROW_SPAN_INVALID":
		return &ChartRowSpanInvalidError{APIError: apiError}
	case "CHART_VARIABLE_TYPE_REQUIRED":
		return &ChartVariableTypeRequiredError{APIError: apiError}
	case "CHART_VARIABLE_VISIBLE_REQUIRED":
		return &ChartVariableVisibleRequiredError{APIError: apiError}
	case "CONTRADICTORY_DASHBOARD_FILTER":
		typedError := &ContradictoryDashboardFilterError{APIError: apiError}
		if len(apiError.ExtraData) != 0 {
			var details ContradictoryDashboardFilterExceptionDetails
			if err := json.Unmarshal(apiError.ExtraData, &details); err == nil {
				typedError.Details = &details
			}
		}
		return typedError
	case "CYCLIC_DASHBOARD_VARIABLE_DEPENDENCY":
		return &CyclicDashboardVariableDependencyError{APIError: apiError}
	case "DASHBOARD_REFRESH_INTERVAL_REQUIRED":
		return &DashboardRefreshIntervalRequiredError{APIError: apiError}
	case "DASHBOARD_REFRESH_INTERVAL_TOO_FAST":
		return &DashboardRefreshIntervalTooFastError{APIError: apiError}
	case "DUPLICATE_ALARM_VARIABLE_NAME":
		return &DuplicateAlarmVariableNameError{APIError: apiError}
	case "DUPLICATE_CHART_ID":
		return &DuplicateChartIdError{APIError: apiError}
	case "DUPLICATE_CHART_VARIABLE_NAME":
		return &DuplicateChartVariableNameError{APIError: apiError}
	case "DUPLICATE_DASHBOARD_FILTER":
		typedError := &DuplicateDashboardFilterError{APIError: apiError}
		if len(apiError.ExtraData) != 0 {
			var details DuplicateDashboardFilterExceptionDetails
			if err := json.Unmarshal(apiError.ExtraData, &details); err == nil {
				typedError.Details = &details
			}
		}
		return typedError
	case "DUPLICATE_DIMENSION_NAME":
		return &DuplicateDimensionNameError{APIError: apiError}
	case "EMAIL_NOTIFICATION_CHANNEL_CANNOT_INCLUDE_WEBHOOK_CONFIG":
		return &EmailNotificationChannelCannotIncludeWebhookConfigError{APIError: apiError}
	case "EMAIL_NOTIFICATION_CHANNEL_CONFIG_REQUIRED":
		return &EmailNotificationChannelConfigRequiredError{APIError: apiError}
	case "ENTRY_REQUIRES_VALUE_OR_STATISTIC_SET":
		return &EntryRequiresValueOrStatisticSetError{APIError: apiError}
	case "ENTRY_TIMESTAMP_IN_FUTURE":
		return &EntryTimestampInFutureError{APIError: apiError}
	case "ENTRY_TIMESTAMP_TOO_OLD":
		return &EntryTimestampTooOldError{APIError: apiError}
	case "EXPRESSION_TOO_COMPLEX":
		return &ExpressionTooComplexError{APIError: apiError}
	case "EXPRESSION_VARIABLE_EXPRESSION_REQUIRED":
		return &ExpressionVariableExpressionRequiredError{APIError: apiError}
	case "INVALID_AGGREGATION":
		return &InvalidAggregationError{APIError: apiError}
	case "INVALID_ALARM_REQUEST":
		return &InvalidAlarmRequestError{APIError: apiError}
	case "INVALID_DASHBOARD_FILTER":
		typedError := &InvalidDashboardFilterError{APIError: apiError}
		if len(apiError.ExtraData) != 0 {
			var details InvalidDashboardFilterExceptionDetails
			if err := json.Unmarshal(apiError.ExtraData, &details); err == nil {
				typedError.Details = &details
			}
		}
		return typedError
	case "INVALID_DASHBOARD_TIME_RANGE":
		return &InvalidDashboardTimeRangeError{APIError: apiError}
	case "INVALID_EXPRESSION":
		return &InvalidExpressionError{APIError: apiError}
	case "INVALID_EXPRESSION_TOKEN":
		return &InvalidExpressionTokenError{APIError: apiError}
	case "INVALID_METRIC_DATA":
		return &InvalidMetricDataError{APIError: apiError}
	case "INVALID_METRIC_QUERY":
		return &InvalidMetricQueryError{APIError: apiError}
	case "INVALID_NUMERIC_EXPRESSION":
		return &InvalidNumericExpressionError{APIError: apiError}
	case "INVALID_OR_EXPIRED_VERIFICATION_CODE":
		return &InvalidOrExpiredVerificationCodeError{APIError: apiError}
	case "INVALID_PAGINATION_TOKEN":
		return &InvalidPaginationTokenError{APIError: apiError}
	case "METRIC_QUERY_TIMESTAMP_IN_FUTURE":
		return &MetricQueryTimestampInFutureError{APIError: apiError}
	case "METRIC_QUERY_TIMESTAMP_TOO_OLD":
		return &MetricQueryTimestampTooOldError{APIError: apiError}
	case "METRIC_VARIABLE_METRIC_NAME_REQUIRED":
		return &MetricVariableMetricNameRequiredError{APIError: apiError}
	case "MISMATCHED_EXPRESSION_PARENTHESES":
		return &MismatchedExpressionParenthesesError{APIError: apiError}
	case "MISSING_EXPRESSION_OPERAND":
		return &MissingExpressionOperandError{APIError: apiError}
	case "MISSING_EXPRESSION_OPERANDS":
		return &MissingExpressionOperandsError{APIError: apiError}
	case "NOTIFICATION_CHANNEL_CONFIG_REQUIRED":
		return &NotificationChannelConfigRequiredError{APIError: apiError}
	case "NOTIFICATION_CHANNEL_IN_USE":
		return &NotificationChannelInUseError{APIError: apiError}
	case "ONLY_EMAIL_NOTIFICATION_CHANNELS_CAN_BE_VERIFIED":
		return &OnlyEmailNotificationChannelsCanBeVerifiedError{APIError: apiError}
	case "RESOURCE_DELETION_IN_PROGRESS":
		return &ResourceDeletionInProgressError{APIError: apiError}
	case "RESOURCE_LIMIT_EXCEEDED":
		typedError := &ResourceLimitExceededError{APIError: apiError}
		if len(apiError.ExtraData) != 0 {
			var details ResourceLimitExceededExceptionDetails
			if err := json.Unmarshal(apiError.ExtraData, &details); err == nil {
				typedError.Details = &details
			}
		}
		return typedError
	case "RESOURCE_NOT_FOUND":
		typedError := &ResourceNotFoundError{APIError: apiError}
		if len(apiError.ExtraData) != 0 {
			var details ResourceNotFoundExceptionDetails
			if err := json.Unmarshal(apiError.ExtraData, &details); err == nil {
				typedError.Details = &details
			}
		}
		return typedError
	case "RESOURCE_UPDATED_CONCURRENTLY":
		return &ResourceUpdatedConcurrentlyError{APIError: apiError}
	case "START_TIME_AFTER_END_TIME":
		return &StartTimeAfterEndTimeError{APIError: apiError}
	case "STATISTIC_SET_INCOMPLETE":
		return &StatisticSetIncompleteError{APIError: apiError}
	case "STATISTIC_SET_INVALID_RANGE":
		return &StatisticSetInvalidRangeError{APIError: apiError}
	case "TOKEN_EXPIRED":
		return &TokenExpiredError{APIError: apiError}
	case "TOO_MANY_DIMENSIONS":
		return &TooManyDimensionsError{APIError: apiError}
	case "TOO_MANY_DIMENSION_COMBINATIONS":
		return &TooManyDimensionCombinationsError{APIError: apiError}
	case "UNAUTHORIZED":
		return &UnauthorizedError{APIError: apiError}
	case "UNSUPPORTED_CHART_VARIABLE_TYPE":
		return &UnsupportedChartVariableTypeError{APIError: apiError}
	case "UNVERIFIED_NOTIFICATION_CHANNEL":
		return &UnverifiedNotificationChannelError{APIError: apiError}
	case "WEBHOOK_NOTIFICATION_CHANNEL_CANNOT_INCLUDE_EMAIL_CONFIG":
		return &WebhookNotificationChannelCannotIncludeEmailConfigError{APIError: apiError}
	case "WEBHOOK_NOTIFICATION_CHANNEL_CONFIG_REQUIRED":
		return &WebhookNotificationChannelConfigRequiredError{APIError: apiError}
	default:
		return apiError
	}
}
