// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/omascloud/sdks/go/core"
)

const endpoint = "https://api.omas.cloud/"

// Client calls the metrics API.
type Client struct {
	client *core.Client
}

// NewClient constructs a metrics API client.
func NewClient(authProvider core.AuthProvider, options ...core.ClientOption) (*Client, error) {
	options = append(options, core.WithAPIErrorDecoder(decodeAPIError))
	client, err := core.NewClient("metrics", endpoint, authProvider, options...)
	if err != nil {
		return nil, err
	}
	return &Client{client: client}, nil
}

// Close releases resources owned by the client.
func (c *Client) Close() error {
	return c.client.Close()
}

// CreateAlarm Create an alarm
func (c *Client) CreateAlarm(
	ctx context.Context,
	request CreateAlarmOperationRequest,
) (*Alarm, error) {
	if err := request.Validate(); err != nil {
		return nil, fmt.Errorf("validate createAlarm request: %w", err)
	}
	path := "/v1/alarms/{alarmName}"
	path = core.ReplacePathParameter(path, "alarmName", request.AlarmName)
	query := url.Values{}
	headers := http.Header{}
	result := new(Alarm)
	err := c.client.Do(ctx, "createAlarm", http.MethodPost, path, query, headers, request, result)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// CreateDashboard Create a new dashboard
func (c *Client) CreateDashboard(
	ctx context.Context,
	request CreateDashboardOperationRequest,
) (*Dashboard, error) {
	if err := request.Validate(); err != nil {
		return nil, fmt.Errorf("validate createDashboard request: %w", err)
	}
	path := "/v1/dashboards"
	query := url.Values{}
	headers := http.Header{}
	result := new(Dashboard)
	err := c.client.Do(ctx, "createDashboard", http.MethodPost, path, query, headers, request, result)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// CreateDashboardEmbed Generate public iframe embed code for a dashboard
func (c *Client) CreateDashboardEmbed(
	ctx context.Context,
	request CreateDashboardEmbedOperationRequest,
) (*CreateDashboardEmbedResponse, error) {
	if err := request.Validate(); err != nil {
		return nil, fmt.Errorf("validate createDashboardEmbed request: %w", err)
	}
	path := "/v1/dashboards/{dashboardId}/embed"
	path = core.ReplacePathParameter(path, "dashboardId", request.DashboardID)
	query := url.Values{}
	headers := http.Header{}
	result := new(CreateDashboardEmbedResponse)
	err := c.client.Do(ctx, "createDashboardEmbed", http.MethodPost, path, query, headers, nil, result)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// CreateNotificationChannel Create a new notification channel
func (c *Client) CreateNotificationChannel(
	ctx context.Context,
	request CreateNotificationChannelOperationRequest,
) (*NotificationChannel, error) {
	if err := request.Validate(); err != nil {
		return nil, fmt.Errorf("validate createNotificationChannel request: %w", err)
	}
	path := "/v1/notification-channels"
	query := url.Values{}
	headers := http.Header{}
	result := new(NotificationChannel)
	err := c.client.Do(ctx, "createNotificationChannel", http.MethodPost, path, query, headers, request, result)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// DeleteAlarm Delete an alarm
func (c *Client) DeleteAlarm(
	ctx context.Context,
	request DeleteAlarmOperationRequest,
) error {
	if err := request.Validate(); err != nil {
		return fmt.Errorf("validate deleteAlarm request: %w", err)
	}
	path := "/v1/alarms/{alarmName}"
	path = core.ReplacePathParameter(path, "alarmName", request.AlarmName)
	query := url.Values{}
	headers := http.Header{}
	return c.client.Do(ctx, "deleteAlarm", http.MethodDelete, path, query, headers, nil, nil)
}

// DeleteDashboard Delete a dashboard
func (c *Client) DeleteDashboard(
	ctx context.Context,
	request DeleteDashboardOperationRequest,
) error {
	if err := request.Validate(); err != nil {
		return fmt.Errorf("validate deleteDashboard request: %w", err)
	}
	path := "/v1/dashboards/{dashboardId}"
	path = core.ReplacePathParameter(path, "dashboardId", request.DashboardID)
	query := url.Values{}
	headers := http.Header{}
	return c.client.Do(ctx, "deleteDashboard", http.MethodDelete, path, query, headers, nil, nil)
}

// DeleteDimension Delete dimension metadata from a metric
func (c *Client) DeleteDimension(
	ctx context.Context,
	request DeleteDimensionOperationRequest,
) error {
	if err := request.Validate(); err != nil {
		return fmt.Errorf("validate deleteDimension request: %w", err)
	}
	path := "/v1/metrics/{metricName}/dimensions/{dimensionName}"
	path = core.ReplacePathParameter(path, "metricName", request.MetricName)
	path = core.ReplacePathParameter(path, "dimensionName", request.DimensionName)
	query := url.Values{}
	headers := http.Header{}
	return c.client.Do(ctx, "deleteDimension", http.MethodDelete, path, query, headers, nil, nil)
}

// DeleteMetric Delete metric
func (c *Client) DeleteMetric(
	ctx context.Context,
	request DeleteMetricOperationRequest,
) error {
	if err := request.Validate(); err != nil {
		return fmt.Errorf("validate deleteMetric request: %w", err)
	}
	path := "/v1/metrics/{metricName}"
	path = core.ReplacePathParameter(path, "metricName", request.MetricName)
	query := url.Values{}
	headers := http.Header{}
	return c.client.Do(ctx, "deleteMetric", http.MethodDelete, path, query, headers, nil, nil)
}

// DeleteNotificationChannel Delete a notification channel
func (c *Client) DeleteNotificationChannel(
	ctx context.Context,
	request DeleteNotificationChannelOperationRequest,
) error {
	if err := request.Validate(); err != nil {
		return fmt.Errorf("validate deleteNotificationChannel request: %w", err)
	}
	path := "/v1/notification-channels/{channelName}"
	path = core.ReplacePathParameter(path, "channelName", request.ChannelName)
	query := url.Values{}
	headers := http.Header{}
	return c.client.Do(ctx, "deleteNotificationChannel", http.MethodDelete, path, query, headers, nil, nil)
}

// GetAlarm Get an alarm
func (c *Client) GetAlarm(
	ctx context.Context,
	request GetAlarmOperationRequest,
) (*Alarm, error) {
	if err := request.Validate(); err != nil {
		return nil, fmt.Errorf("validate getAlarm request: %w", err)
	}
	path := "/v1/alarms/{alarmName}"
	path = core.ReplacePathParameter(path, "alarmName", request.AlarmName)
	query := url.Values{}
	headers := http.Header{}
	result := new(Alarm)
	err := c.client.Do(ctx, "getAlarm", http.MethodGet, path, query, headers, nil, result)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// GetDashboard Get a dashboard by id
func (c *Client) GetDashboard(
	ctx context.Context,
	request GetDashboardOperationRequest,
) (*Dashboard, error) {
	if err := request.Validate(); err != nil {
		return nil, fmt.Errorf("validate getDashboard request: %w", err)
	}
	path := "/v1/dashboards/{dashboardId}"
	path = core.ReplacePathParameter(path, "dashboardId", request.DashboardID)
	query := url.Values{}
	headers := http.Header{}
	result := new(Dashboard)
	err := c.client.Do(ctx, "getDashboard", http.MethodGet, path, query, headers, nil, result)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// GetDimensionValues Get available values for a dimension
func (c *Client) GetDimensionValues(
	ctx context.Context,
	request GetDimensionValuesOperationRequest,
) (*GetDimensionValuesResponse, error) {
	if err := request.Validate(); err != nil {
		return nil, fmt.Errorf("validate getDimensionValues request: %w", err)
	}
	path := "/v1/metrics/{metricName}/dimensions/{dimensionName}/values"
	path = core.ReplacePathParameter(path, "metricName", request.MetricName)
	path = core.ReplacePathParameter(path, "dimensionName", request.DimensionName)
	query := url.Values{}
	headers := http.Header{}
	result := new(GetDimensionValuesResponse)
	err := c.client.Do(ctx, "getDimensionValues", http.MethodGet, path, query, headers, nil, result)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// GetMetricData Get metrics data
func (c *Client) GetMetricData(
	ctx context.Context,
	request GetMetricDataOperationRequest,
) (*GetMetricDataResponse, error) {
	if err := request.Validate(); err != nil {
		return nil, fmt.Errorf("validate getMetricData request: %w", err)
	}
	path := "/v1/metrics/{metricName}"
	path = core.ReplacePathParameter(path, "metricName", request.MetricName)
	query := url.Values{}
	core.AddQueryParameter(query, "resolution", request.Resolution)
	core.AddQueryParameter(query, "aggregation", request.Aggregation)
	core.AddQueryParameter(query, "startTimestamp", request.StartTimestamp)
	core.AddQueryParameter(query, "endTimestamp", request.EndTimestamp)
	core.AddQueryParameter(query, "maxResults", request.MaxResults)
	core.AddQueryParameter(query, "includeDimensions", request.IncludeDimensions)
	core.AddQueryParameter(query, "excludeDimensions", request.ExcludeDimensions)
	core.AddQueryParameter(query, "nextToken", request.NextToken)
	headers := http.Header{}
	result := new(GetMetricDataResponse)
	err := c.client.Do(ctx, "getMetricData", http.MethodGet, path, query, headers, nil, result)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// GetNotificationChannel Get a notification channel by name
func (c *Client) GetNotificationChannel(
	ctx context.Context,
	request GetNotificationChannelOperationRequest,
) (*NotificationChannel, error) {
	if err := request.Validate(); err != nil {
		return nil, fmt.Errorf("validate getNotificationChannel request: %w", err)
	}
	path := "/v1/notification-channels/{channelName}"
	path = core.ReplacePathParameter(path, "channelName", request.ChannelName)
	query := url.Values{}
	headers := http.Header{}
	result := new(NotificationChannel)
	err := c.client.Do(ctx, "getNotificationChannel", http.MethodGet, path, query, headers, nil, result)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// ListAlarmHistory List alarm history
func (c *Client) ListAlarmHistory(
	ctx context.Context,
	request ListAlarmHistoryOperationRequest,
) (*ListAlarmHistoryResponse, error) {
	if err := request.Validate(); err != nil {
		return nil, fmt.Errorf("validate listAlarmHistory request: %w", err)
	}
	path := "/v1/alarms/{alarmName}/history"
	path = core.ReplacePathParameter(path, "alarmName", request.AlarmName)
	query := url.Values{}
	core.AddQueryParameter(query, "maxResults", request.MaxResults)
	core.AddQueryParameter(query, "nextToken", request.NextToken)
	headers := http.Header{}
	result := new(ListAlarmHistoryResponse)
	err := c.client.Do(ctx, "listAlarmHistory", http.MethodGet, path, query, headers, nil, result)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// ListAlarms List all alarms
func (c *Client) ListAlarms(
	ctx context.Context,
	request ListAlarmsOperationRequest,
) (*ListAlarmsResponse, error) {
	if err := request.Validate(); err != nil {
		return nil, fmt.Errorf("validate listAlarms request: %w", err)
	}
	path := "/v1/alarms"
	query := url.Values{}
	core.AddQueryParameter(query, "maxResults", request.MaxResults)
	core.AddQueryParameter(query, "nextToken", request.NextToken)
	core.AddQueryParameter(query, "query", request.Query)
	core.AddQueryParameter(query, "statuses", request.Statuses)
	headers := http.Header{}
	result := new(ListAlarmsResponse)
	err := c.client.Do(ctx, "listAlarms", http.MethodGet, path, query, headers, nil, result)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// ListDashboards List all dashboards for the authenticated user
func (c *Client) ListDashboards(
	ctx context.Context,
	request ListDashboardsOperationRequest,
) (*ListDashboardsResponse, error) {
	if err := request.Validate(); err != nil {
		return nil, fmt.Errorf("validate listDashboards request: %w", err)
	}
	path := "/v1/dashboards"
	query := url.Values{}
	core.AddQueryParameter(query, "maxResults", request.MaxResults)
	core.AddQueryParameter(query, "nextToken", request.NextToken)
	headers := http.Header{}
	result := new(ListDashboardsResponse)
	err := c.client.Do(ctx, "listDashboards", http.MethodGet, path, query, headers, nil, result)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// ListMetrics List all metrics
func (c *Client) ListMetrics(
	ctx context.Context,
	request ListMetricsOperationRequest,
) (*ListMetricsResponse, error) {
	if err := request.Validate(); err != nil {
		return nil, fmt.Errorf("validate listMetrics request: %w", err)
	}
	path := "/v1/metrics"
	query := url.Values{}
	core.AddQueryParameter(query, "maxResults", request.MaxResults)
	core.AddQueryParameter(query, "nextToken", request.NextToken)
	core.AddQueryParameter(query, "query", request.Query)
	core.AddQueryParameter(query, "dimensions", request.Dimensions)
	core.AddQueryParameter(query, "dimensionValues", request.DimensionValues)
	headers := http.Header{}
	result := new(ListMetricsResponse)
	err := c.client.Do(ctx, "listMetrics", http.MethodGet, path, query, headers, nil, result)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// ListNotificationChannels List all notification channels for the authenticated user
func (c *Client) ListNotificationChannels(
	ctx context.Context,
	request ListNotificationChannelsOperationRequest,
) (*ListNotificationChannelsResponse, error) {
	if err := request.Validate(); err != nil {
		return nil, fmt.Errorf("validate listNotificationChannels request: %w", err)
	}
	path := "/v1/notification-channels"
	query := url.Values{}
	core.AddQueryParameter(query, "maxResults", request.MaxResults)
	core.AddQueryParameter(query, "nextToken", request.NextToken)
	headers := http.Header{}
	result := new(ListNotificationChannelsResponse)
	err := c.client.Do(ctx, "listNotificationChannels", http.MethodGet, path, query, headers, nil, result)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// PutMetricData Submit metrics data
func (c *Client) PutMetricData(
	ctx context.Context,
	request PutMetricDataOperationRequest,
) error {
	if err := request.Validate(); err != nil {
		return fmt.Errorf("validate putMetricData request: %w", err)
	}
	path := "/v1/metrics/{metricName}"
	path = core.ReplacePathParameter(path, "metricName", request.MetricName)
	query := url.Values{}
	headers := http.Header{}
	return c.client.Do(ctx, "putMetricData", http.MethodPost, path, query, headers, request, nil)
}

// UpdateAlarm Update an alarm
func (c *Client) UpdateAlarm(
	ctx context.Context,
	request UpdateAlarmOperationRequest,
) (*Alarm, error) {
	if err := request.Validate(); err != nil {
		return nil, fmt.Errorf("validate updateAlarm request: %w", err)
	}
	path := "/v1/alarms/{alarmName}"
	path = core.ReplacePathParameter(path, "alarmName", request.AlarmName)
	query := url.Values{}
	headers := http.Header{}
	result := new(Alarm)
	err := c.client.Do(ctx, "updateAlarm", http.MethodPut, path, query, headers, request, result)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// UpdateDashboard Update a dashboard
func (c *Client) UpdateDashboard(
	ctx context.Context,
	request UpdateDashboardOperationRequest,
) (*Dashboard, error) {
	if err := request.Validate(); err != nil {
		return nil, fmt.Errorf("validate updateDashboard request: %w", err)
	}
	path := "/v1/dashboards/{dashboardId}"
	path = core.ReplacePathParameter(path, "dashboardId", request.DashboardID)
	query := url.Values{}
	headers := http.Header{}
	result := new(Dashboard)
	err := c.client.Do(ctx, "updateDashboard", http.MethodPut, path, query, headers, request, result)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// UpdateNotificationChannel Update a notification channel
func (c *Client) UpdateNotificationChannel(
	ctx context.Context,
	request UpdateNotificationChannelOperationRequest,
) (*NotificationChannel, error) {
	if err := request.Validate(); err != nil {
		return nil, fmt.Errorf("validate updateNotificationChannel request: %w", err)
	}
	path := "/v1/notification-channels/{channelName}"
	path = core.ReplacePathParameter(path, "channelName", request.ChannelName)
	query := url.Values{}
	headers := http.Header{}
	result := new(NotificationChannel)
	err := c.client.Do(ctx, "updateNotificationChannel", http.MethodPut, path, query, headers, request, result)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// VerifyNotificationChannel Verify an email notification channel
func (c *Client) VerifyNotificationChannel(
	ctx context.Context,
	request VerifyNotificationChannelOperationRequest,
) (*NotificationChannel, error) {
	if err := request.Validate(); err != nil {
		return nil, fmt.Errorf("validate verifyNotificationChannel request: %w", err)
	}
	path := "/v1/notification-channels/{channelName}/verify"
	path = core.ReplacePathParameter(path, "channelName", request.ChannelName)
	query := url.Values{}
	headers := http.Header{}
	result := new(NotificationChannel)
	err := c.client.Do(ctx, "verifyNotificationChannel", http.MethodPost, path, query, headers, request, result)
	if err != nil {
		return nil, err
	}
	return result, nil
}
