// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

import (
	"fmt"
	"regexp"
	"strings"
)

// DeleteDimensionOperationRequest Parameters for Delete dimension metadata from a metric.
type DeleteDimensionOperationRequest struct {
	// Metric name.
	MetricName string `json:"-"`
	// Dimension name.
	DimensionName string `json:"-"`
}

// Validate checks request values against the OpenAPI constraints.
func (v DeleteDimensionOperationRequest) Validate() error {
	if strings.TrimSpace(string(v.MetricName)) == "" {
		return fmt.Errorf("metricName: must not be blank")
	}
	if len(v.MetricName) > 255 {
		return fmt.Errorf("metricName: length must be at most 255")
	}
	if matched, err := regexp.MatchString("^[A-Za-z0-9_.-]+$", string(v.MetricName)); err != nil || !matched {
		return fmt.Errorf("metricName: has an invalid format")
	}
	if strings.TrimSpace(string(v.DimensionName)) == "" {
		return fmt.Errorf("dimensionName: must not be blank")
	}
	if len(v.DimensionName) > 255 {
		return fmt.Errorf("dimensionName: length must be at most 255")
	}
	if matched, err := regexp.MatchString("^[A-Za-z0-9_-]+$", string(v.DimensionName)); err != nil || !matched {
		return fmt.Errorf("dimensionName: has an invalid format")
	}
	return nil
}
