// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// MetricDimensionFacet contains API model data.
type MetricDimensionFacet struct {
	Name   string                      `json:"name"`
	Count  int64                       `json:"count"`
	Values []MetricDimensionValueFacet `json:"values"`
}
