// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// Metric contains API model data.
type Metric struct {
	// Metric name using only letters, numbers, dots, underscores, and hyphens.
	Name string `json:"name"`
	// List of dimension names associated with this metric.
	Dimensions []string `json:"dimensions,omitempty"`
}
