// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// AlarmSummary contains API model data.
type AlarmSummary struct {
	// Identifier using only letters, numbers, underscores, and hyphens.
	Name               *string            `json:"name,omitempty"`
	Status             *AlarmStatus       `json:"status,omitempty"`
	NotificationStatus NotificationStatus `json:"notificationStatus"`
	// The number of notification channels configured for the alarm.
	NotificationChannelCount int32 `json:"notificationChannelCount"`
	// Timestamp of the latest alarm status update, in milliseconds since Unix epoch.
	LastStatusUpdate *int64 `json:"lastStatusUpdate,omitempty"`
}
