// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

import (
	"encoding/json"
	"fmt"
)

// DimensionFilterOperator defines the allowed values for DimensionFilterOperator.
type DimensionFilterOperator string

const (
	DIMENSIONFILTEROPERATOR_EQUALS     DimensionFilterOperator = "EQUALS"
	DIMENSIONFILTEROPERATOR_NOT_EQUALS DimensionFilterOperator = "NOT_EQUALS"
)

// IsValid reports whether v is a value defined by the API contract.
func (v DimensionFilterOperator) IsValid() bool {
	switch v {
	case DIMENSIONFILTEROPERATOR_EQUALS:
		return true
	case DIMENSIONFILTEROPERATOR_NOT_EQUALS:
		return true
	default:
		return false
	}
}

// UnmarshalJSON rejects values not defined by the API contract.
func (v *DimensionFilterOperator) UnmarshalJSON(data []byte) error {
	var value string
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	decoded := DimensionFilterOperator(value)
	if !decoded.IsValid() {
		return fmt.Errorf("invalid DimensionFilterOperator value: %v", value)
	}
	*v = decoded
	return nil
}
