// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// NotificationChannelConfig contains API model data.
type NotificationChannelConfig struct {
	Webhook *WebhookConfig `json:"webhook,omitempty"`
	Email   *EmailConfig   `json:"email,omitempty"`
}
