// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

import (
	"fmt"
)

// ListMetricsOperationRequest Parameters for List all metrics.
type ListMetricsOperationRequest struct {
	// The maximum number of metrics to return in a single response page.
	MaxResults *int32 `json:"-"`
	// Pagination token to retrieve the next page of metrics for the same filters.
	NextToken *string `json:"-"`
	// Case-insensitive text contained in the metric name.
	Query *string `json:"-"`
	// Dimension names that every returned metric must expose.
	Dimensions []string `json:"-"`
	// Dimension values to match, formatted as 'name:value'. Multiple values for one name are ORed; different names are ANDed.
	DimensionValues []string `json:"-"`
}

// Validate checks request values against the OpenAPI constraints.
func (v ListMetricsOperationRequest) Validate() error {
	if v.MaxResults != nil && *v.MaxResults < 1 {
		return fmt.Errorf("maxResults: must be at least 1")
	}
	if v.MaxResults != nil && *v.MaxResults > 100 {
		return fmt.Errorf("maxResults: must be at most 100")
	}
	if v.NextToken != nil && len(*v.NextToken) > 4096 {
		return fmt.Errorf("nextToken: length must be at most 4096")
	}
	if v.Query != nil && len(*v.Query) > 255 {
		return fmt.Errorf("query: length must be at most 255")
	}
	if v.Dimensions != nil && len(v.Dimensions) > 30 {
		return fmt.Errorf("dimensions: must contain at most 30 items")
	}
	if v.DimensionValues != nil && len(v.DimensionValues) > 100 {
		return fmt.Errorf("dimensionValues: must contain at most 100 items")
	}
	return nil
}
