// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// CreateDashboardRequest contains API model data.
type CreateDashboardRequest struct {
	// Display name using words made of letters, numbers, underscores, and hyphens separated by single spaces.
	Name string `json:"name"`
	// Flag to enable automatic refreshing.
	AutoRefreshEnabled *bool `json:"autoRefreshEnabled,omitempty"`
	// Automatic refresh interval in milliseconds (5s to 5min).
	RefreshIntervalMs *int32 `json:"refreshIntervalMs,omitempty"`
}
