// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

import (
	"fmt"
	"regexp"
	"strings"
)

// GetAlarmOperationRequest Parameters for Get an alarm.
type GetAlarmOperationRequest struct {
	// Alarm name.
	AlarmName string `json:"-"`
}

// Validate checks request values against the OpenAPI constraints.
func (v GetAlarmOperationRequest) Validate() error {
	if strings.TrimSpace(string(v.AlarmName)) == "" {
		return fmt.Errorf("alarmName: must not be blank")
	}
	if len(v.AlarmName) > 255 {
		return fmt.Errorf("alarmName: length must be at most 255")
	}
	if matched, err := regexp.MatchString("^[A-Za-z0-9_-]+$", string(v.AlarmName)); err != nil || !matched {
		return fmt.Errorf("alarmName: has an invalid format")
	}
	return nil
}
