// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// GetMetricDataResponse contains API model data.
type GetMetricDataResponse struct {
	// The list of retrieved data points.
	Entries []DataPointResult `json:"entries,omitempty"`
	// Token used for retrieving the next page of results.
	NextToken *string `json:"nextToken,omitempty"`
}
