// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

import (
	"fmt"
	"regexp"
	"strings"
)

// UpdateAlarmOperationRequest Parameters for Update an alarm.
type UpdateAlarmOperationRequest struct {
	// Alarm name.
	AlarmName string `json:"-"`
	// List of metric variables that the alarm expression monitors.
	Variables []AlarmVariable `json:"variables"`
	// The threshold expression (e.g., 'A > 90'). Must use variable names defined in 'variables'.
	Expression string `json:"expression"`
	// The duration in minutes over which the metric data is evaluated.
	EvaluationPeriodInMin int32 `json:"evaluationPeriodInMin"`
	// The number of consecutive data points that must breach the threshold to trigger the alarm.
	DatapointsToAlarm int32 `json:"datapointsToAlarm"`
	// Resolution in seconds.
	Resolution         int32              `json:"resolution"`
	TreatMissingDataAs TreatMissingDataAs `json:"treatMissingDataAs"`
	// List of names of notification channels to alert when the alarm status changes.
	NotificationChannels []string `json:"notificationChannels,omitempty"`
}

// Validate checks request values against the OpenAPI constraints.
func (v UpdateAlarmOperationRequest) Validate() error {
	if strings.TrimSpace(string(v.AlarmName)) == "" {
		return fmt.Errorf("alarmName: must not be blank")
	}
	if len(v.AlarmName) > 255 {
		return fmt.Errorf("alarmName: length must be at most 255")
	}
	if matched, err := regexp.MatchString("^[A-Za-z0-9_-]+$", string(v.AlarmName)); err != nil || !matched {
		return fmt.Errorf("alarmName: has an invalid format")
	}
	if v.Variables == nil {
		return fmt.Errorf("variables: is required")
	}
	if len(v.Variables) < 1 {
		return fmt.Errorf("variables: must contain at least 1 items")
	}
	if len(v.Variables) > 10 {
		return fmt.Errorf("variables: must contain at most 10 items")
	}
	if strings.TrimSpace(string(v.Expression)) == "" {
		return fmt.Errorf("expression: must not be blank")
	}
	if len(v.Expression) < 1 {
		return fmt.Errorf("expression: length must be at least 1")
	}
	if len(v.Expression) > 1024 {
		return fmt.Errorf("expression: length must be at most 1024")
	}
	if v.EvaluationPeriodInMin < 1 {
		return fmt.Errorf("evaluationPeriodInMin: must be at least 1")
	}
	if v.EvaluationPeriodInMin > 1440 {
		return fmt.Errorf("evaluationPeriodInMin: must be at most 1440")
	}
	if v.DatapointsToAlarm < 1 {
		return fmt.Errorf("datapointsToAlarm: must be at least 1")
	}
	if v.DatapointsToAlarm > 1440 {
		return fmt.Errorf("datapointsToAlarm: must be at most 1440")
	}
	if v.Resolution < 1 {
		return fmt.Errorf("resolution: must be at least 1")
	}
	if v.Resolution > 3600 {
		return fmt.Errorf("resolution: must be at most 3600")
	}
	if v.NotificationChannels != nil && len(v.NotificationChannels) > 10 {
		return fmt.Errorf("notificationChannels: must contain at most 10 items")
	}
	return nil
}
