// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// DataPoint contains API model data.
type DataPoint struct {
	// The timestamp for the data point in milliseconds since Unix epoch. When omitted, the server receipt time is used. Historical data may be submitted up to 24 hours late.
	Timestamp *int64 `json:"timestamp,omitempty"`
	// The single numeric value of the data point.
	Value        *float32      `json:"value,omitempty"`
	StatisticSet *StatisticSet `json:"statisticSet,omitempty"`
	// Dimensions that qualify the data point.
	Dimensions []Dimension `json:"dimensions,omitempty"`
	// Resolution in seconds.
	Resolution *int32 `json:"resolution,omitempty"`
}
