// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

import (
	"fmt"
	"regexp"
	"strings"
)

// PutMetricDataOperationRequest Parameters for Submit metrics data.
type PutMetricDataOperationRequest struct {
	// Metric name.
	MetricName string `json:"-"`
	// A list of 1 to 1000 data points to be published.
	Entries []DataPoint `json:"entries"`
}

// Validate checks request values against the OpenAPI constraints.
func (v PutMetricDataOperationRequest) Validate() error {
	if strings.TrimSpace(string(v.MetricName)) == "" {
		return fmt.Errorf("metricName: must not be blank")
	}
	if len(v.MetricName) > 255 {
		return fmt.Errorf("metricName: length must be at most 255")
	}
	if matched, err := regexp.MatchString("^[A-Za-z0-9_.-]+$", string(v.MetricName)); err != nil || !matched {
		return fmt.Errorf("metricName: has an invalid format")
	}
	if v.Entries == nil {
		return fmt.Errorf("entries: is required")
	}
	if len(v.Entries) < 1 {
		return fmt.Errorf("entries: must contain at least 1 items")
	}
	if len(v.Entries) > 1000 {
		return fmt.Errorf("entries: must contain at most 1000 items")
	}
	return nil
}
