// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

import (
	"fmt"
	"reflect"
)

// ListAlarmsOperationRequest Parameters for List all alarms.
type ListAlarmsOperationRequest struct {
	// The maximum number of alarms to return in a single response page.
	MaxResults *int32 `json:"-"`
	// Pagination token to retrieve the next page of alarms if the current result set is truncated.
	NextToken *string `json:"-"`
	// Case-insensitive text contained in the alarm name.
	Query *string `json:"-"`
	// The alarm statuses to return. Missing or empty selects all statuses.
	Statuses []AlarmStatus `json:"-"`
}

// Validate checks request values against the OpenAPI constraints.
func (v ListAlarmsOperationRequest) Validate() error {
	if v.MaxResults != nil && *v.MaxResults < 1 {
		return fmt.Errorf("maxResults: must be at least 1")
	}
	if v.MaxResults != nil && *v.MaxResults > 100 {
		return fmt.Errorf("maxResults: must be at most 100")
	}
	if v.NextToken != nil && len(*v.NextToken) > 4096 {
		return fmt.Errorf("nextToken: length must be at most 4096")
	}
	if v.Query != nil && len(*v.Query) > 255 {
		return fmt.Errorf("query: length must be at most 255")
	}
	for left := range v.Statuses {
		for right := left + 1; right < len(v.Statuses); right++ {
			if reflect.DeepEqual((v.Statuses)[left], (v.Statuses)[right]) {
				return fmt.Errorf("statuses: items must be unique")
			}
		}
	}
	return nil
}
