// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// AlarmHistoryEntry contains API model data.
type AlarmHistoryEntry struct {
	OldStatus *AlarmStatus `json:"oldStatus,omitempty"`
	NewStatus *AlarmStatus `json:"newStatus,omitempty"`
	// Timestamp when the transition was recorded, in milliseconds since Unix epoch.
	CreatedAt *int64 `json:"createdAt,omitempty"`
}
