// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// StartTimeAfterEndTimeException Start time must not be bigger than end time
type StartTimeAfterEndTimeException struct {
	ErrorCode string                  `json:"errorCode"`
	Error     string                  `json:"error"`
	ExtraData *map[string]interface{} `json:"extraData,omitempty"`
}
