// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// ContradictoryDashboardFilterException Contradictory dimension filters for variable: %s
type ContradictoryDashboardFilterException struct {
	ErrorCode string                                        `json:"errorCode"`
	Error     string                                        `json:"error"`
	ExtraData *ContradictoryDashboardFilterExceptionDetails `json:"extraData,omitempty"`
}
