// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

import (
	"fmt"
	"regexp"
	"strings"
)

// ListAlarmHistoryOperationRequest Parameters for List alarm history.
type ListAlarmHistoryOperationRequest struct {
	// Alarm name.
	AlarmName string `json:"-"`
	// The maximum number of history entries to return in a single response page.
	MaxResults *int32 `json:"-"`
	// Pagination token to retrieve the next page of older alarm history entries if the current result set is truncated.
	NextToken *string `json:"-"`
}

// Validate checks request values against the OpenAPI constraints.
func (v ListAlarmHistoryOperationRequest) Validate() error {
	if strings.TrimSpace(string(v.AlarmName)) == "" {
		return fmt.Errorf("alarmName: must not be blank")
	}
	if len(v.AlarmName) > 255 {
		return fmt.Errorf("alarmName: length must be at most 255")
	}
	if matched, err := regexp.MatchString("^[A-Za-z0-9_-]+$", string(v.AlarmName)); err != nil || !matched {
		return fmt.Errorf("alarmName: has an invalid format")
	}
	if v.MaxResults != nil && *v.MaxResults < 1 {
		return fmt.Errorf("maxResults: must be at least 1")
	}
	if v.MaxResults != nil && *v.MaxResults > 100 {
		return fmt.Errorf("maxResults: must be at most 100")
	}
	if v.NextToken != nil && len(*v.NextToken) > 4096 {
		return fmt.Errorf("nextToken: length must be at most 4096")
	}
	return nil
}
