// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

import (
	"encoding/json"
	"fmt"
)

// AlarmStatus defines the allowed values for AlarmStatus.
type AlarmStatus string

const (
	ALARMSTATUS_OK                AlarmStatus = "OK"
	ALARMSTATUS_IN_ALARM          AlarmStatus = "IN_ALARM"
	ALARMSTATUS_INSUFFICIENT_DATA AlarmStatus = "INSUFFICIENT_DATA"
)

// IsValid reports whether v is a value defined by the API contract.
func (v AlarmStatus) IsValid() bool {
	switch v {
	case ALARMSTATUS_OK:
		return true
	case ALARMSTATUS_IN_ALARM:
		return true
	case ALARMSTATUS_INSUFFICIENT_DATA:
		return true
	default:
		return false
	}
}

// UnmarshalJSON rejects values not defined by the API contract.
func (v *AlarmStatus) UnmarshalJSON(data []byte) error {
	var value string
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	decoded := AlarmStatus(value)
	if !decoded.IsValid() {
		return fmt.Errorf("invalid AlarmStatus value: %v", value)
	}
	*v = decoded
	return nil
}
