// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// DimensionFilterConfig contains API model data.
type DimensionFilterConfig struct {
	// Identifier using only letters, numbers, underscores, and hyphens.
	DimensionName string `json:"dimensionName"`
	// The value to compare against.
	DimensionValue string                  `json:"dimensionValue"`
	Operator       DimensionFilterOperator `json:"operator"`
}
