// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

import (
	"fmt"
	"regexp"
	"strings"
)

// DeleteMetricOperationRequest Parameters for Delete metric.
type DeleteMetricOperationRequest struct {
	// Metric name.
	MetricName string `json:"-"`
}

// Validate checks request values against the OpenAPI constraints.
func (v DeleteMetricOperationRequest) Validate() error {
	if strings.TrimSpace(string(v.MetricName)) == "" {
		return fmt.Errorf("metricName: must not be blank")
	}
	if len(v.MetricName) > 255 {
		return fmt.Errorf("metricName: length must be at most 255")
	}
	if matched, err := regexp.MatchString("^[A-Za-z0-9_.-]+$", string(v.MetricName)); err != nil || !matched {
		return fmt.Errorf("metricName: has an invalid format")
	}
	return nil
}
