// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

import (
	"encoding/json"
	"fmt"
)

// ChartVariableType defines the allowed values for ChartVariableType.
type ChartVariableType string

const (
	CHARTVARIABLETYPE_METRIC     ChartVariableType = "METRIC"
	CHARTVARIABLETYPE_EXPRESSION ChartVariableType = "EXPRESSION"
)

// IsValid reports whether v is a value defined by the API contract.
func (v ChartVariableType) IsValid() bool {
	switch v {
	case CHARTVARIABLETYPE_METRIC:
		return true
	case CHARTVARIABLETYPE_EXPRESSION:
		return true
	default:
		return false
	}
}

// UnmarshalJSON rejects values not defined by the API contract.
func (v *ChartVariableType) UnmarshalJSON(data []byte) error {
	var value string
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	decoded := ChartVariableType(value)
	if !decoded.IsValid() {
		return fmt.Errorf("invalid ChartVariableType value: %v", value)
	}
	*v = decoded
	return nil
}
