// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// StatisticSet contains API model data.
type StatisticSet struct {
	// The average of all values in the sample set.
	Avg float32 `json:"avg"`
	// The minimum value in the sample set.
	Min float32 `json:"min"`
	// The maximum value in the sample set.
	Max float32 `json:"max"`
	// The number of samples used for the statistics.
	SampleCount int64 `json:"sampleCount"`
}
