// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// EmailConfig contains API model data.
type EmailConfig struct {
	// Email address.
	Email string `json:"email"`
}
