// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

import (
	"fmt"
)

// ListDashboardsOperationRequest Parameters for List all dashboards for the authenticated user.
type ListDashboardsOperationRequest struct {
	// The maximum number of dashboards to return in a single response page.
	MaxResults *int32 `json:"-"`
	// Pagination token to retrieve the next page of dashboards if the current result set is truncated.
	NextToken *string `json:"-"`
}

// Validate checks request values against the OpenAPI constraints.
func (v ListDashboardsOperationRequest) Validate() error {
	if v.MaxResults != nil && *v.MaxResults < 1 {
		return fmt.Errorf("maxResults: must be at least 1")
	}
	if v.MaxResults != nil && *v.MaxResults > 100 {
		return fmt.Errorf("maxResults: must be at most 100")
	}
	if v.NextToken != nil && len(*v.NextToken) > 4096 {
		return fmt.Errorf("nextToken: length must be at most 4096")
	}
	return nil
}
