// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

import (
	"encoding/json"
	"fmt"
)

// NotificationChannelType defines the allowed values for NotificationChannelType.
type NotificationChannelType string

const (
	NOTIFICATIONCHANNELTYPE_WEBHOOK NotificationChannelType = "WEBHOOK"
	NOTIFICATIONCHANNELTYPE_EMAIL   NotificationChannelType = "EMAIL"
)

// IsValid reports whether v is a value defined by the API contract.
func (v NotificationChannelType) IsValid() bool {
	switch v {
	case NOTIFICATIONCHANNELTYPE_WEBHOOK:
		return true
	case NOTIFICATIONCHANNELTYPE_EMAIL:
		return true
	default:
		return false
	}
}

// UnmarshalJSON rejects values not defined by the API contract.
func (v *NotificationChannelType) UnmarshalJSON(data []byte) error {
	var value string
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	decoded := NotificationChannelType(value)
	if !decoded.IsValid() {
		return fmt.Errorf("invalid NotificationChannelType value: %v", value)
	}
	*v = decoded
	return nil
}
