// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// ListAlarmsResponse contains API model data.
type ListAlarmsResponse struct {
	// The list of alarm summaries.
	Alarms []AlarmSummary `json:"alarms,omitempty"`
	// Pagination token to retrieve the next set of alarms.
	NextToken *string `json:"nextToken,omitempty"`
	// The number of alarms matching the query and selected status.
	TotalCount   int64             `json:"totalCount"`
	StatusCounts AlarmStatusCounts `json:"statusCounts"`
}
