// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// Dashboard contains API model data.
type Dashboard struct {
	// Unique identifier for the dashboard.
	ID string `json:"id"`
	// Display name using words made of letters, numbers, underscores, and hyphens separated by single spaces.
	Name string `json:"name"`
	// List of chart configurations that make up the dashboard.
	Charts []ChartConfig `json:"charts"`
	// Flag to enable or disable automatic data refreshing for the dashboard.
	AutoRefreshEnabled *bool `json:"autoRefreshEnabled,omitempty"`
	// The interval in milliseconds at which the dashboard data is automatically refreshed.
	RefreshIntervalMs *int32 `json:"refreshIntervalMs,omitempty"`
	// Timestamp when the dashboard was created, in milliseconds since Unix epoch.
	CreatedAt *int64 `json:"createdAt,omitempty"`
	// Timestamp when the dashboard was last updated, in milliseconds since Unix epoch.
	UpdatedAt *int64 `json:"updatedAt,omitempty"`
}
