// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// ChartRowInvalidException Chart must fit within dashboard rows 0 through 3599
type ChartRowInvalidException struct {
	ErrorCode string                  `json:"errorCode"`
	Error     string                  `json:"error"`
	ExtraData *map[string]interface{} `json:"extraData,omitempty"`
}
