// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// MetricDimensionValueFacet contains API model data.
type MetricDimensionValueFacet struct {
	Value string `json:"value"`
	Count int64  `json:"count"`
}
