// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

import (
	"fmt"
	"regexp"
	"strings"
)

// DeleteDashboardOperationRequest Parameters for Delete a dashboard.
type DeleteDashboardOperationRequest struct {
	// Dashboard identifier.
	DashboardID string `json:"-"`
}

// Validate checks request values against the OpenAPI constraints.
func (v DeleteDashboardOperationRequest) Validate() error {
	if strings.TrimSpace(string(v.DashboardID)) == "" {
		return fmt.Errorf("dashboardId: must not be blank")
	}
	if len(v.DashboardID) > 255 {
		return fmt.Errorf("dashboardId: length must be at most 255")
	}
	if matched, err := regexp.MatchString("^[A-Za-z0-9_-]+$", string(v.DashboardID)); err != nil || !matched {
		return fmt.Errorf("dashboardId: has an invalid format")
	}
	return nil
}
