// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

import (
	"encoding/json"
	"fmt"
)

// NotificationStatus defines the allowed values for NotificationStatus.
type NotificationStatus string

const (
	NOTIFICATIONSTATUS_OK     NotificationStatus = "OK"
	NOTIFICATIONSTATUS_FAILED NotificationStatus = "FAILED"
)

// IsValid reports whether v is a value defined by the API contract.
func (v NotificationStatus) IsValid() bool {
	switch v {
	case NOTIFICATIONSTATUS_OK:
		return true
	case NOTIFICATIONSTATUS_FAILED:
		return true
	default:
		return false
	}
}

// UnmarshalJSON rejects values not defined by the API contract.
func (v *NotificationStatus) UnmarshalJSON(data []byte) error {
	var value string
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	decoded := NotificationStatus(value)
	if !decoded.IsValid() {
		return fmt.Errorf("invalid NotificationStatus value: %v", value)
	}
	*v = decoded
	return nil
}
