// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// GetDimensionValuesResponse contains API model data.
type GetDimensionValuesResponse struct {
	// The list of unique values for the requested dimension.
	Values []string `json:"values,omitempty"`
}
