// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// PutMetricDataRequest contains API model data.
type PutMetricDataRequest struct {
	// A list of 1 to 1000 data points to be published.
	Entries []DataPoint `json:"entries"`
}
