// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// ListMetricsResponse contains API model data.
type ListMetricsResponse struct {
	Metrics []Metric `json:"metrics"`
	// Token used for retrieving the next page of results.
	NextToken *string `json:"nextToken,omitempty"`
	// The total number of metrics matching the current filters.
	TotalCount int64 `json:"totalCount"`
	// Workspace-wide dimension facets; value options are populated for selected dimensions.
	DimensionFacets []MetricDimensionFacet `json:"dimensionFacets"`
}
