// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// TimeRangeConfig contains API model data.
type TimeRangeConfig struct {
	// A positive relative duration using seconds, minutes, hours, or days (for example, 30m or 2d).
	Preset string `json:"preset"`
	// Resolution in seconds.
	Resolution int32 `json:"resolution"`
}
