// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// AlarmVariable contains API model data.
type AlarmVariable struct {
	// Expression variable name. Must start with a letter or underscore and may contain only letters, numbers, and underscores.
	Name string `json:"name"`
	// Metric name using only letters, numbers, dots, underscores, and hyphens.
	MetricName string `json:"metricName"`
	// Dimension filters to include for the metric query.
	IncludeDimensions []Dimension `json:"includeDimensions,omitempty"`
	// Dimension filters to exclude for the metric query.
	ExcludeDimensions []Dimension `json:"excludeDimensions,omitempty"`
	// Aggregation expression to apply to metric data. Supported forms are sum, max, min, avg, count, percentile(<0-100>), trimmed_mean(<lower>;<upper>), trimmed_mean(<lower>;), and trimmed_mean(;<upper>). Trimmed-mean bounds are percentages from 0 to 100, and at least one bound must be present.
	Aggregation string `json:"aggregation"`
}
