// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// ListDashboardsResponse contains API model data.
type ListDashboardsResponse struct {
	// The list of dashboard summaries.
	Dashboards []DashboardSummary `json:"dashboards,omitempty"`
	// Pagination token to retrieve the next set of dashboards.
	NextToken *string `json:"nextToken,omitempty"`
}
