// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// ResourceNotFoundExceptionDetails contains API model data.
type ResourceNotFoundExceptionDetails struct {
	ChartID      *string `json:"chartId"`
	VariableName *string `json:"variableName"`
	Field        *string `json:"field"`
}
