// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// VerifyNotificationChannelRequest contains API model data.
type VerifyNotificationChannelRequest struct {
	// Six-digit verification code.
	Code string `json:"code"`
}
