// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// ListAlarmHistoryResponse contains API model data.
type ListAlarmHistoryResponse struct {
	// The list of alarm status transitions, ordered from newest to oldest.
	History []AlarmHistoryEntry `json:"history,omitempty"`
	// Pagination token to retrieve the next set of older alarm history entries.
	NextToken *string `json:"nextToken,omitempty"`
}
