// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// CreateDashboardEmbedResponse contains API model data.
type CreateDashboardEmbedResponse struct {
	// The specialized access token for the embedded view.
	Token string `json:"token"`
	// UUID token identifier.
	TokenID string `json:"tokenId"`
	// The restricted authorization role generated for this embed.
	Role string `json:"role"`
	// Ready-to-use HTML iframe snippet for embedding the dashboard.
	Iframe string `json:"iframe"`
	// Timestamp when the embed access expires, in milliseconds since Unix epoch.
	ExpiresAt int64 `json:"expiresAt"`
}
