// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// ContradictoryDashboardFilterExceptionDetails contains API model data.
type ContradictoryDashboardFilterExceptionDetails struct {
	ChartID      *string `json:"chartId"`
	VariableName *string `json:"variableName"`
	FilterIndex  int32   `json:"filterIndex"`
	Field        *string `json:"field"`
}
