// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// ChartConfig contains API model data.
type ChartConfig struct {
	// Unique identifier for the chart within the dashboard.
	ID string `json:"id"`
	// The title displayed at the top of the chart.
	Title     string     `json:"title"`
	ChartType *ChartType `json:"chartType,omitempty"`
	// Display unit label for the chart axis or values (e.g., 'ms', 'req/s', '%').
	Unit *string `json:"unit,omitempty"`
	// Vertical position of the chart in the dashboard grid (starts from 0).
	Row *int32 `json:"row,omitempty"`
	// Horizontal position of the chart in the dashboard grid (0-23).
	Column *int32 `json:"column,omitempty"`
	// Width of the chart in grid columns (1-24).
	ColSpan *int32 `json:"colSpan,omitempty"`
	// Height of the chart in grid rows.
	RowSpan *int32 `json:"rowSpan,omitempty"`
	// The metric variables or expressions used as data sources for this chart.
	Variables []ChartVariable `json:"variables"`
	TimeRange TimeRangeConfig `json:"timeRange"`
}
