// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// CreateAlarmRequest contains API model data.
type CreateAlarmRequest struct {
	// List of metric variables that the alarm expression monitors.
	Variables []AlarmVariable `json:"variables"`
	// The threshold expression (e.g., 'A > 90'). Must use variable names defined in 'variables'.
	Expression string `json:"expression"`
	// The duration in minutes over which the metric data is evaluated.
	EvaluationPeriodInMin int32 `json:"evaluationPeriodInMin"`
	// The number of consecutive data points that must breach the threshold to trigger the alarm.
	DatapointsToAlarm int32 `json:"datapointsToAlarm"`
	// Resolution in seconds.
	Resolution         int32              `json:"resolution"`
	TreatMissingDataAs TreatMissingDataAs `json:"treatMissingDataAs"`
	// List of names of notification channels to alert when the alarm status changes.
	NotificationChannels []string `json:"notificationChannels,omitempty"`
}
