// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// Alarm contains API model data.
type Alarm struct {
	// Identifier using only letters, numbers, underscores, and hyphens.
	Name *string `json:"name,omitempty"`
	// List of metric variables that the alarm expression monitors.
	Variables []AlarmVariable `json:"variables,omitempty"`
	// The threshold expression (e.g., 'A > 90').
	Expression *string `json:"expression,omitempty"`
	// The duration in minutes over which the metric data is evaluated.
	EvaluationPeriodInMin *int32 `json:"evaluationPeriodInMin,omitempty"`
	// The number of consecutive data points that must breach the threshold to trigger the alarm.
	DatapointsToAlarm *int32 `json:"datapointsToAlarm,omitempty"`
	// Resolution in seconds.
	Resolution         *int32              `json:"resolution,omitempty"`
	TreatMissingDataAs *TreatMissingDataAs `json:"treatMissingDataAs,omitempty"`
	Status             *AlarmStatus        `json:"status,omitempty"`
	NotificationStatus *NotificationStatus `json:"notificationStatus,omitempty"`
	// List of names of notification channels to alert when the alarm status changes.
	NotificationChannels []string `json:"notificationChannels,omitempty"`
}
