// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

import (
	"encoding/json"
	"fmt"
)

// TreatMissingDataAs defines the allowed values for TreatMissingDataAs.
type TreatMissingDataAs string

const (
	TREATMISSINGDATAAS_BREACHING     TreatMissingDataAs = "BREACHING"
	TREATMISSINGDATAAS_NOT_BREACHING TreatMissingDataAs = "NOT_BREACHING"
	TREATMISSINGDATAAS_MISSING       TreatMissingDataAs = "MISSING"
)

// IsValid reports whether v is a value defined by the API contract.
func (v TreatMissingDataAs) IsValid() bool {
	switch v {
	case TREATMISSINGDATAAS_BREACHING:
		return true
	case TREATMISSINGDATAAS_NOT_BREACHING:
		return true
	case TREATMISSINGDATAAS_MISSING:
		return true
	default:
		return false
	}
}

// UnmarshalJSON rejects values not defined by the API contract.
func (v *TreatMissingDataAs) UnmarshalJSON(data []byte) error {
	var value string
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	decoded := TreatMissingDataAs(value)
	if !decoded.IsValid() {
		return fmt.Errorf("invalid TreatMissingDataAs value: %v", value)
	}
	*v = decoded
	return nil
}
