// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// ResourceLimitExceededExceptionDetails contains API model data.
type ResourceLimitExceededExceptionDetails struct {
	Resource *string `json:"resource"`
	Limit    int32   `json:"limit"`
}
