// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

import (
	"fmt"
	"regexp"
	"strings"
)

// CreateDashboardOperationRequest Parameters for Create a new dashboard.
type CreateDashboardOperationRequest struct {
	// Display name using words made of letters, numbers, underscores, and hyphens separated by single spaces.
	Name string `json:"name"`
	// Flag to enable automatic refreshing.
	AutoRefreshEnabled *bool `json:"autoRefreshEnabled,omitempty"`
	// Automatic refresh interval in milliseconds (5s to 5min).
	RefreshIntervalMs *int32 `json:"refreshIntervalMs,omitempty"`
}

// Validate checks request values against the OpenAPI constraints.
func (v CreateDashboardOperationRequest) Validate() error {
	if strings.TrimSpace(string(v.Name)) == "" {
		return fmt.Errorf("name: must not be blank")
	}
	if len(v.Name) < 1 {
		return fmt.Errorf("name: length must be at least 1")
	}
	if len(v.Name) > 128 {
		return fmt.Errorf("name: length must be at most 128")
	}
	if matched, err := regexp.MatchString("^[A-Za-z0-9_-]+(?: [A-Za-z0-9_-]+)*$", string(v.Name)); err != nil || !matched {
		return fmt.Errorf("name: has an invalid format")
	}
	if v.RefreshIntervalMs != nil && *v.RefreshIntervalMs < 5000 {
		return fmt.Errorf("refreshIntervalMs: must be at least 5000")
	}
	if v.RefreshIntervalMs != nil && *v.RefreshIntervalMs > 300000 {
		return fmt.Errorf("refreshIntervalMs: must be at most 300000")
	}
	return nil
}
