// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// ResourceLimitExceededException Resource limit exceeded
type ResourceLimitExceededException struct {
	ErrorCode string                                 `json:"errorCode"`
	Error     string                                 `json:"error"`
	ExtraData *ResourceLimitExceededExceptionDetails `json:"extraData,omitempty"`
}
