// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

import (
	"fmt"
	"regexp"
	"strings"
)

// GetMetricDataOperationRequest Parameters for Get metrics data.
type GetMetricDataOperationRequest struct {
	// The unique name of the metric to retrieve data for.
	MetricName string `json:"-"`
	// The granularity of the returned data points, in seconds. Must be a multiple of the metric's original resolution.
	Resolution *int32 `json:"-"`
	// The aggregation expression to apply to the data points within each resolution bucket.
	Aggregation *string `json:"-"`
	// The beginning of the time range to query, in milliseconds since Unix epoch.
	StartTimestamp int64 `json:"-"`
	// The end of the time range to query, in milliseconds since Unix epoch. Defaults to the current time if not specified.
	EndTimestamp *int64 `json:"-"`
	// The maximum number of data points to return in a single response page.
	MaxResults *int32 `json:"-"`
	// Filter data points by these dimensions. Format each item as 'name:value'. Filters that match no data return an empty result.
	IncludeDimensions []string `json:"-"`
	// Exclude data points that match these dimensions. Format each item as 'name:value'. Filters that match no data return an empty result.
	ExcludeDimensions []string `json:"-"`
	// Pagination token to retrieve the next page of results if the current result set is truncated.
	NextToken *string `json:"-"`
}

// Validate checks request values against the OpenAPI constraints.
func (v GetMetricDataOperationRequest) Validate() error {
	if strings.TrimSpace(string(v.MetricName)) == "" {
		return fmt.Errorf("metricName: must not be blank")
	}
	if len(v.MetricName) > 255 {
		return fmt.Errorf("metricName: length must be at most 255")
	}
	if matched, err := regexp.MatchString("^[A-Za-z0-9_.-]+$", string(v.MetricName)); err != nil || !matched {
		return fmt.Errorf("metricName: has an invalid format")
	}
	if v.Resolution != nil && *v.Resolution < 1 {
		return fmt.Errorf("resolution: must be at least 1")
	}
	if v.Resolution != nil && *v.Resolution > 3600 {
		return fmt.Errorf("resolution: must be at most 3600")
	}
	if v.Aggregation != nil && len(*v.Aggregation) < 3 {
		return fmt.Errorf("aggregation: length must be at least 3")
	}
	if v.Aggregation != nil && len(*v.Aggregation) > 128 {
		return fmt.Errorf("aggregation: length must be at most 128")
	}
	if v.MaxResults != nil && *v.MaxResults < 1 {
		return fmt.Errorf("maxResults: must be at least 1")
	}
	if v.MaxResults != nil && *v.MaxResults > 10000 {
		return fmt.Errorf("maxResults: must be at most 10000")
	}
	if v.IncludeDimensions != nil && len(v.IncludeDimensions) > 30 {
		return fmt.Errorf("includeDimensions: must contain at most 30 items")
	}
	if v.ExcludeDimensions != nil && len(v.ExcludeDimensions) > 30 {
		return fmt.Errorf("excludeDimensions: must contain at most 30 items")
	}
	if v.NextToken != nil && len(*v.NextToken) > 1024 {
		return fmt.Errorf("nextToken: length must be at most 1024")
	}
	return nil
}
