// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// UpdateDashboardRequest contains API model data.
type UpdateDashboardRequest struct {
	// Display name using words made of letters, numbers, underscores, and hyphens separated by single spaces.
	Name *string `json:"name,omitempty"`
	// The updated list of chart configurations for the dashboard.
	Charts []ChartConfig `json:"charts,omitempty"`
	// Flag to enable automatic refreshing.
	AutoRefreshEnabled *bool `json:"autoRefreshEnabled,omitempty"`
	// Automatic refresh interval in milliseconds (5s to 5min).
	RefreshIntervalMs *int32 `json:"refreshIntervalMs,omitempty"`
}
