// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

import (
	"fmt"
	"regexp"
	"strings"
)

// CreateNotificationChannelOperationRequest Parameters for Create a new notification channel.
type CreateNotificationChannelOperationRequest struct {
	// Identifier using only letters, numbers, underscores, and hyphens.
	Name   string                    `json:"name"`
	Type   NotificationChannelType   `json:"type"`
	Config NotificationChannelConfig `json:"config"`
}

// Validate checks request values against the OpenAPI constraints.
func (v CreateNotificationChannelOperationRequest) Validate() error {
	if strings.TrimSpace(string(v.Name)) == "" {
		return fmt.Errorf("name: must not be blank")
	}
	if len(v.Name) > 255 {
		return fmt.Errorf("name: length must be at most 255")
	}
	if matched, err := regexp.MatchString("^[A-Za-z0-9_-]+$", string(v.Name)); err != nil || !matched {
		return fmt.Errorf("name: has an invalid format")
	}
	return nil
}
