// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

import (
	"encoding/json"
	"fmt"
)

// ChartType defines the allowed values for ChartType.
type ChartType string

const (
	CHARTTYPE_LINE   ChartType = "LINE"
	CHARTTYPE_NUMBER ChartType = "NUMBER"
)

// IsValid reports whether v is a value defined by the API contract.
func (v ChartType) IsValid() bool {
	switch v {
	case CHARTTYPE_LINE:
		return true
	case CHARTTYPE_NUMBER:
		return true
	default:
		return false
	}
}

// UnmarshalJSON rejects values not defined by the API contract.
func (v *ChartType) UnmarshalJSON(data []byte) error {
	var value string
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	decoded := ChartType(value)
	if !decoded.IsValid() {
		return fmt.Errorf("invalid ChartType value: %v", value)
	}
	*v = decoded
	return nil
}
