// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// ResourceNotFoundException Resource not found
type ResourceNotFoundException struct {
	ErrorCode string                            `json:"errorCode"`
	Error     string                            `json:"error"`
	ExtraData *ResourceNotFoundExceptionDetails `json:"extraData,omitempty"`
}
