// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// ListNotificationChannelsResponse contains API model data.
type ListNotificationChannelsResponse struct {
	// List of notification channels configured for the account.
	Channels []NotificationChannel `json:"channels,omitempty"`
	// Pagination token to retrieve the next set of notification channels.
	NextToken *string `json:"nextToken,omitempty"`
}
