// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// AlarmStatusCounts contains API model data.
type AlarmStatusCounts struct {
	Ok               int64 `json:"ok"`
	InAlarm          int64 `json:"inAlarm"`
	InsufficientData int64 `json:"insufficientData"`
}
