// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// Dimension contains API model data.
type Dimension struct {
	// Identifier using only letters, numbers, underscores, and hyphens.
	Name string `json:"name"`
	// The value of the dimension.
	Value string `json:"value"`
}
