// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// NotificationChannel contains API model data.
type NotificationChannel struct {
	// Identifier using only letters, numbers, underscores, and hyphens.
	Name   string                    `json:"name"`
	Type   NotificationChannelType   `json:"type"`
	Config NotificationChannelConfig `json:"config"`
	// Indicates whether the channel has been successfully verified (e.g., via email code).
	Verified bool `json:"verified"`
}
