// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

import (
	"fmt"
	"regexp"
	"strings"
)

// VerifyNotificationChannelOperationRequest Parameters for Verify an email notification channel.
type VerifyNotificationChannelOperationRequest struct {
	// Notification channel name.
	ChannelName string `json:"-"`
	// Six-digit verification code.
	Code string `json:"code"`
}

// Validate checks request values against the OpenAPI constraints.
func (v VerifyNotificationChannelOperationRequest) Validate() error {
	if strings.TrimSpace(string(v.ChannelName)) == "" {
		return fmt.Errorf("channelName: must not be blank")
	}
	if len(v.ChannelName) > 255 {
		return fmt.Errorf("channelName: length must be at most 255")
	}
	if matched, err := regexp.MatchString("^[A-Za-z0-9_-]+$", string(v.ChannelName)); err != nil || !matched {
		return fmt.Errorf("channelName: has an invalid format")
	}
	if strings.TrimSpace(string(v.Code)) == "" {
		return fmt.Errorf("code: must not be blank")
	}
	if matched, err := regexp.MatchString("^[0-9]{6}$", string(v.Code)); err != nil || !matched {
		return fmt.Errorf("code: has an invalid format")
	}
	return nil
}
