// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// InvalidDashboardFilterException Invalid dimension filter at index %s for variable: %s
type InvalidDashboardFilterException struct {
	ErrorCode string                                  `json:"errorCode"`
	Error     string                                  `json:"error"`
	ExtraData *InvalidDashboardFilterExceptionDetails `json:"extraData,omitempty"`
}
