// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// DashboardRefreshIntervalTooFastException refreshIntervalMs must be at least the finest chart resolution of %s seconds
type DashboardRefreshIntervalTooFastException struct {
	ErrorCode string                  `json:"errorCode"`
	Error     string                  `json:"error"`
	ExtraData *map[string]interface{} `json:"extraData,omitempty"`
}
