// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// DashboardSummary contains API model data.
type DashboardSummary struct {
	// Unique identifier for the dashboard.
	ID string `json:"id"`
	// Display name using words made of letters, numbers, underscores, and hyphens separated by single spaces.
	Name string `json:"name"`
	// Total number of charts configured in this dashboard.
	ChartCount *int32 `json:"chartCount,omitempty"`
	// Timestamp when the dashboard was last updated, in milliseconds since Unix epoch.
	UpdatedAt *int64 `json:"updatedAt,omitempty"`
}
