// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// OnlyEmailNotificationChannelsCanBeVerifiedException Only email notification channels can be verified
type OnlyEmailNotificationChannelsCanBeVerifiedException struct {
	ErrorCode string                  `json:"errorCode"`
	Error     string                  `json:"error"`
	ExtraData *map[string]interface{} `json:"extraData,omitempty"`
}
