// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

import (
	"fmt"
	"regexp"
	"strings"
)

// UpdateDashboardOperationRequest Parameters for Update a dashboard.
type UpdateDashboardOperationRequest struct {
	// Dashboard identifier.
	DashboardID string `json:"-"`
	// Display name using words made of letters, numbers, underscores, and hyphens separated by single spaces.
	Name *string `json:"name,omitempty"`
	// The updated list of chart configurations for the dashboard.
	Charts []ChartConfig `json:"charts,omitempty"`
	// Flag to enable automatic refreshing.
	AutoRefreshEnabled *bool `json:"autoRefreshEnabled,omitempty"`
	// Automatic refresh interval in milliseconds (5s to 5min).
	RefreshIntervalMs *int32 `json:"refreshIntervalMs,omitempty"`
}

// Validate checks request values against the OpenAPI constraints.
func (v UpdateDashboardOperationRequest) Validate() error {
	if strings.TrimSpace(string(v.DashboardID)) == "" {
		return fmt.Errorf("dashboardId: must not be blank")
	}
	if len(v.DashboardID) > 255 {
		return fmt.Errorf("dashboardId: length must be at most 255")
	}
	if matched, err := regexp.MatchString("^[A-Za-z0-9_-]+$", string(v.DashboardID)); err != nil || !matched {
		return fmt.Errorf("dashboardId: has an invalid format")
	}
	if v.Name != nil && len(*v.Name) < 1 {
		return fmt.Errorf("name: length must be at least 1")
	}
	if v.Name != nil && len(*v.Name) > 128 {
		return fmt.Errorf("name: length must be at most 128")
	}
	if v.Name != nil {
		if matched, err := regexp.MatchString("^[A-Za-z0-9_-]+(?: [A-Za-z0-9_-]+)*$", string(*v.Name)); err != nil || !matched {
			return fmt.Errorf("name: has an invalid format")
		}
	}
	if v.Charts != nil && len(v.Charts) > 100 {
		return fmt.Errorf("charts: must contain at most 100 items")
	}
	if v.RefreshIntervalMs != nil && *v.RefreshIntervalMs < 5000 {
		return fmt.Errorf("refreshIntervalMs: must be at least 5000")
	}
	if v.RefreshIntervalMs != nil && *v.RefreshIntervalMs > 300000 {
		return fmt.Errorf("refreshIntervalMs: must be at most 300000")
	}
	return nil
}
