// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// WebhookConfig contains API model data.
type WebhookConfig struct {
	// The target URL to receive POST requests.
	Url string `json:"url"`
	// Optional HTTP headers to include in the webhook request.
	Headers *map[string]string `json:"headers,omitempty"`
}
