// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// DuplicateDashboardFilterException Duplicate dimension filter for variable: %s
type DuplicateDashboardFilterException struct {
	ErrorCode string                                    `json:"errorCode"`
	Error     string                                    `json:"error"`
	ExtraData *DuplicateDashboardFilterExceptionDetails `json:"extraData,omitempty"`
}
