// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// UpdateNotificationChannelRequest contains API model data.
type UpdateNotificationChannelRequest struct {
	Config NotificationChannelConfig `json:"config"`
}
