// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// CreateNotificationChannelRequest contains API model data.
type CreateNotificationChannelRequest struct {
	// Identifier using only letters, numbers, underscores, and hyphens.
	Name   string                    `json:"name"`
	Type   NotificationChannelType   `json:"type"`
	Config NotificationChannelConfig `json:"config"`
}
