// Copyright (c) 2026 Omas Cloud
//
// SPDX-License-Identifier: MIT
//
// Code generated by the Omas Go SDK generator. DO NOT EDIT.

package metrics

// ChartVariable contains API model data.
type ChartVariable struct {
	// Expression variable name. Must start with a letter or underscore and may contain only letters, numbers, and underscores.
	Name string `json:"name"`
	// Optional human-readable label for the variable in the chart legend.
	DisplayName *string `json:"displayName,omitempty"`
	// Whether this variable's data should be visible on the chart.
	Visible bool              `json:"visible"`
	Type    ChartVariableType `json:"type"`
	// Metric name using only letters, numbers, dots, underscores, and hyphens.
	MetricName *string `json:"metricName,omitempty"`
	// Aggregation expression to apply to metric data. Supported forms are sum, max, min, avg, count, percentile(<0-100>), trimmed_mean(<lower>;<upper>), trimmed_mean(<lower>;), and trimmed_mean(;<upper>). Trimmed-mean bounds are percentages from 0 to 100, and at least one bound must be present.
	Aggregation *string `json:"aggregation,omitempty"`
	// Dimension filters to apply to the metric query.
	Filters []DimensionFilterConfig `json:"filters,omitempty"`
	// The mathematical expression to evaluate (required if type is EXPRESSION).
	Expression *string `json:"expression,omitempty"`
}
